---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fluentd-logs
  namespace: logging
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client
