apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: cloudflare
data:
    credentials.json: ewoiQWNjb3VudFRhZyI6IjQ2MDczNDEwN2IzZTc1Y2EwMjk1NGM0NDUyMzE1MzE3IiwKIlR1bm5lbElEIjoiYjE2ZTRkZjEtMmYyMi00NTEyLWE3YmMtMjliMWVkMTFkNzU0IiwKIlR1bm5lbFNlY3JldCI6Ik1sOWRWbVI1YlZoYkpqRXphWDBsU21WNGQyMU1ia0k2Y2lwVVdtMUxWems9Igp9
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRUxrOU52a1Jod1pJdjIx
            R0FZdVJoOUlKYnprbE5mem52SEFkUU1scW5rCnN1ODVvQjRubU5GbnNGSEFPZDAx
            d1J3VUhCeUJOWDJmbHNaNGdmbEtBaE0KLS0tIFBwV0xjQTVpbDRpNGdDZVA0TndN
            bVYrTUhaMjVsQ3hrYmhSTy9tUzBSYncKK+AN4Ab4ZmISVmf2AvpGTmjTaHl9rigi
            gEqLcFOAUPZ0o0RZroKCc3919dz/IhUFuaCTuEX3wC6Ga8nOZxSCJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T19:50:50Z"
    mac: ENC[AES256_GCM,data:1hJBM6ydhgsQ82uGJ7/nx8VAxx9DtK3vb6MVGbbQ8rf0OMy10Y4q12RNJdIoLIGYQh3gpF5WtdyhnP1ep5kbZERwNH56s6FWGbRGcIr+WSqbvHA4M+AFHivB8ukMv6WJLh+eGSN4HF0tRvrGD8a2IXJT1jtcCOBxdEjHJ4SDtrQ=,iv:l6XogM/8Jyy5cEfIRpl9fXWNGM+nwEpcrL0RpsGJao0=,tag:STJZC2bKrreCNYsQXYQPHQ==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml|object-storage-configs.yaml|api-token)$
    version: 3.7.1
