pipeline {
    agent { label 'k8s'}
    parameters {
        booleanParam(name: 'FORCE_DEPLOY', defaultValue: false, description: 'Force deployment ignoring changeset')
    }
    environment {
        API_SERVER = "https://${params.K8S_API_HOST}:${params.K8S_API_PORT}"
        CLUSTER_NAME = "${params.K8S_CLUSTER}"
        CONTEXT_NAME = "${params.K8S_CONTEXT}"
        DEPLOYMENT_DIR = "${params.DEPLOYMENT_DIR}"
        DEPLOYMENT_NAME = "metrics-server"
    }
    stages {
        
        stage('Checkout') {
            when {
                anyOf {
                    changeset "**/${env.CHART_DIR}/**"
                    expression { return params.FORCE_DEPLOY }
                }
            }
            steps {
                git branch: 'main',
                url: 'https://github.com/nazmang/k8s.git'
            }
        }
        stage('Prepare Kubernetes') {
            when {
                anyOf {
                    changeset "**/${env.CHART_DIR}/**"
                    expression { return params.FORCE_DEPLOY }
                }
            }
            steps {
                withCredentials([string(credentialsId: 'K8S_JENKINS_TOKEN', variable: 'K8S_TOKEN')]) {
                    sh """
                        kubectl config set-cluster ${CLUSTER_NAME} --server=${API_SERVER} --insecure-skip-tls-verify=true
                        kubectl config set-credentials jenkins --token=${K8S_TOKEN}
                        kubectl config set-context ${CONTEXT_NAME} --cluster=${CLUSTER_NAME} --user=jenkins
                        kubectl config use-context ${CONTEXT_NAME}
                    """
                }
            }
        }
        stage('Apply Manifest') {
            when {
                anyOf {
                    changeset "**/${env.CHART_DIR}/**"
                    expression { return params.FORCE_DEPLOY }
                }
            }
            steps {
                dir("${env.DEPLOYMENT_DIR}") {
                    sh """
                    export PATH="$HOME/.local/bin:$PATH"
                    kubectl apply -k . 
                    """
                }
            }
        }
    }
}
