global:
  defaultStorageClass: "nfs-client"

auth:
  enabled: true
  existingSecret: redis-auth
  existingSecretPasswordKey: redis-password

tls:
  enabled: false
  existingSecret: redis-tls
  authClients: true
  certCAFilename: ca.crt
  certFilename: tls.crt
  certKeyFilename: tls.key

architecture: standalone

master:
  persistence:
    enabled: false

replica:
  replicaCount: 0
