apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: local
    namespace: argocd
spec:
    description: Project for local k8s cluster
    sourceRepos:
        - https://github.com/nazmang/k8s.git
        - https://kubernetes-sigs.github.io/external-dns/
        - https://aquasecurity.github.io/helm-charts/
        - https://github.com/raoulx24/trivy-operator-dashboard.git
        - https://*.github.io/*
        - https://*.github.com/*
    destinations:
        - namespace: '*'
          server: https://kubernetes.default.svc
    clusterResourceWhitelist:
        - group: '*'
          kind: '*'
    namespaceResourceWhitelist:
        - group: '*'
          kind: '*'
    orphanedResources:
        warn: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZaTR5NnVYVUwxaHBWcnRo
            aXdId1Q4dVNCQTdYM1ZSbk5lejZBaWxxYnpRClRtQjJVMUhsQ2tlSGN4T1MxajU0
            NFl5bWkzeDFKU3hhbHlIRVR1QmxXVUkKLS0tIEUvMCt2VndWcDhPdjlQNmw1QnU0
            elJ6b09LRVJXWC9HakpTdDM3S0V6Q0UKcEQ7njLtj6JKPtkMrez6HDz9r3RZnfH4
            Fh1TuKwEENf8XHuZjHFRjNfMu/IRjHcMUHaHUVUVXi5V/LzJC46+6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-19T15:31:44Z"
    mac: ENC[AES256_GCM,data:QyeNYlUAXmh7T2L2G4Dj8HlyD4Swc6qRqzGmd1KwhTnqsfBymHI3VHjIBm8rbBGp8OMMiqyxH40+DqFaUys4PNwJflWmCkO9w52nMxrYtRujQSSYO8wbYzGrvVY47xBhZLvxVMB1WU3wn2TYwq1/3CL1UWHJ4HbEObGPV9Jx718=,iv:8yIeGUl4zMIw51dUCY+jwi+jiuvssvalxJpSYGkT/pQ=,tag:ale54Y3uRPi4DizkEcikag==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token)$
    version: 3.7.1
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: apps-root
    namespace: argocd
spec:
    project: local
    source:
        repoURL: https://github.com/nazmang/k8s.git
        targetRevision: HEAD
        path: apps/
    destination:
        server: https://kubernetes.default.svc
        namespace: argocd
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZaTR5NnVYVUwxaHBWcnRo
            aXdId1Q4dVNCQTdYM1ZSbk5lejZBaWxxYnpRClRtQjJVMUhsQ2tlSGN4T1MxajU0
            NFl5bWkzeDFKU3hhbHlIRVR1QmxXVUkKLS0tIEUvMCt2VndWcDhPdjlQNmw1QnU0
            elJ6b09LRVJXWC9HakpTdDM3S0V6Q0UKcEQ7njLtj6JKPtkMrez6HDz9r3RZnfH4
            Fh1TuKwEENf8XHuZjHFRjNfMu/IRjHcMUHaHUVUVXi5V/LzJC46+6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-19T15:31:44Z"
    mac: ENC[AES256_GCM,data:QyeNYlUAXmh7T2L2G4Dj8HlyD4Swc6qRqzGmd1KwhTnqsfBymHI3VHjIBm8rbBGp8OMMiqyxH40+DqFaUys4PNwJflWmCkO9w52nMxrYtRujQSSYO8wbYzGrvVY47xBhZLvxVMB1WU3wn2TYwq1/3CL1UWHJ4HbEObGPV9Jx718=,iv:8yIeGUl4zMIw51dUCY+jwi+jiuvssvalxJpSYGkT/pQ=,tag:ale54Y3uRPi4DizkEcikag==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: sops-age-key
    namespace: argocd
type: Opaque
stringData:
    SOPS_AGE_KEY: ENC[AES256_GCM,data:w1TxL7Srts3d6G2887eUlMQZ8mPV276ADRUNMByzkRDVecmgTWPliOwwVcki7PEqowFpAIgQyODQUjp4Og0GGYsqptw36TR9dLk=,iv:JKvMQIpYqo18nqhXEoWtTbdZ/bTaFx1XnBGr4527ltE=,tag:/iBwtphJagWytdtR/XJSfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZaTR5NnVYVUwxaHBWcnRo
            aXdId1Q4dVNCQTdYM1ZSbk5lejZBaWxxYnpRClRtQjJVMUhsQ2tlSGN4T1MxajU0
            NFl5bWkzeDFKU3hhbHlIRVR1QmxXVUkKLS0tIEUvMCt2VndWcDhPdjlQNmw1QnU0
            elJ6b09LRVJXWC9HakpTdDM3S0V6Q0UKcEQ7njLtj6JKPtkMrez6HDz9r3RZnfH4
            Fh1TuKwEENf8XHuZjHFRjNfMu/IRjHcMUHaHUVUVXi5V/LzJC46+6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-19T15:31:44Z"
    mac: ENC[AES256_GCM,data:QyeNYlUAXmh7T2L2G4Dj8HlyD4Swc6qRqzGmd1KwhTnqsfBymHI3VHjIBm8rbBGp8OMMiqyxH40+DqFaUys4PNwJflWmCkO9w52nMxrYtRujQSSYO8wbYzGrvVY47xBhZLvxVMB1WU3wn2TYwq1/3CL1UWHJ4HbEObGPV9Jx718=,iv:8yIeGUl4zMIw51dUCY+jwi+jiuvssvalxJpSYGkT/pQ=,tag:ale54Y3uRPi4DizkEcikag==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token)$
    version: 3.7.1
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: argocd-application-controller-hpa
    namespace: argocd
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: argocd-argo-cd-app-controller
    minReplicas: 1
    maxReplicas: 3
    metrics:
        - type: Resource
          resource:
            name: cpu
            target:
                type: Utilization
                averageUtilization: 70
        - type: Resource
          resource:
            name: memory
            target:
                type: Utilization
                averageUtilization: 95
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZaTR5NnVYVUwxaHBWcnRo
            aXdId1Q4dVNCQTdYM1ZSbk5lejZBaWxxYnpRClRtQjJVMUhsQ2tlSGN4T1MxajU0
            NFl5bWkzeDFKU3hhbHlIRVR1QmxXVUkKLS0tIEUvMCt2VndWcDhPdjlQNmw1QnU0
            elJ6b09LRVJXWC9HakpTdDM3S0V6Q0UKcEQ7njLtj6JKPtkMrez6HDz9r3RZnfH4
            Fh1TuKwEENf8XHuZjHFRjNfMu/IRjHcMUHaHUVUVXi5V/LzJC46+6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-19T15:31:44Z"
    mac: ENC[AES256_GCM,data:QyeNYlUAXmh7T2L2G4Dj8HlyD4Swc6qRqzGmd1KwhTnqsfBymHI3VHjIBm8rbBGp8OMMiqyxH40+DqFaUys4PNwJflWmCkO9w52nMxrYtRujQSSYO8wbYzGrvVY47xBhZLvxVMB1WU3wn2TYwq1/3CL1UWHJ4HbEObGPV9Jx718=,iv:8yIeGUl4zMIw51dUCY+jwi+jiuvssvalxJpSYGkT/pQ=,tag:ale54Y3uRPi4DizkEcikag==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token)$
    version: 3.7.1
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: argocd-argo-cd-repo-server-hpa
    namespace: argocd
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: argocd-argo-cd-repo-server
    minReplicas: 1
    maxReplicas: 3
    metrics:
        - type: Resource
          resource:
            name: cpu
            target:
                type: Utilization
                averageUtilization: 70
        - type: Resource
          resource:
            name: memory
            target:
                type: Utilization
                averageUtilization: 95
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: ConfigManagementPlugin
# metadata:
#   name: sops-decrypt
#   namespace: argocd
# spec:
#   version: v1.0
#   init:
#     command: ["/bin/sh", "-c"]
#     args:
#       - |
#         set -euo pipefail
#         echo "[CMP:init] preparing sops binary (v3.10.2)..."
#         VERSION="v3.10.2"
#         ARCH=$(uname -m)
#         case "$ARCH" in
#           x86_64|amd64) ARCH="amd64" ;;
#           aarch64|arm64) ARCH="arm64" ;;
#           armv7l|armv7) ARCH="arm" ;;
#           *) echo "[CMP:init] Unsupported arch: $ARCH"; exit 1 ;;
#         esac
#         OS=$(uname -s | tr '[:upper:]' '[:lower:]') # linux/darwin
#         URL="https://github.com/getsops/sops/releases/download/v${VERSION}/sops-v${VERSION}.${OS}.${ARCH}"
#         echo "[CMP:init] Downloading SOPS from: $URL"
#         # -fS: fail on http error and show errors, -L for redirects
#         curl -fSL -o /tmp/sops "${URL}"
#         chmod +x /tmp/sops
#         /tmp/sops --version || (echo "[CMP:init] sops failed to run"; exit 1)
#         echo "[CMP:init] sops ready at /tmp/sops (v${VERSION})"
#   generate:
#     command: ["/bin/sh", "-c"]
#     args:
#       - |
#         set -euo pipefail
#         echo "[CMP:generate] start"
#         # Prefer system sops if present, otherwise use downloaded /tmp/sops
#         if command -v sops >/dev/null 2>&1 ; then
#           SOPS_BIN=$(command -v sops)
#         elif [ -x /tmp/sops ]; then
#           SOPS_BIN=/tmp/sops
#         else
#           echo "[CMP:generate] sops not found"; exit 1
#         fi
#         echo "[CMP:generate] using sops: ${SOPS_BIN}"
#         # Decrypt all .env.enc -> .env (in the repo/directory)
#         for f in $(find . -type f -name '*.env.enc' 2>/dev/null || true); do
#           out="${f%.enc}"
#           echo "[CMP:generate] decrypting ${f} -> ${out}"
#           "${SOPS_BIN}" --decrypt --output "${out}" "${f}"
#         done
#         # Optional: decrypt argocd.values.enc -> argocd.values.yaml (if used)
#         if [ -f "argocd.values.enc.yaml" ]; then
#           echo "[CMP:generate] decrypting argocd.values.enc.yaml -> argocd.values.yaml"
#           "${SOPS_BIN}" --decrypt --output argocd.values.yaml argocd.values.enc.yaml
#         fi
#         echo "[CMP:generate] running kustomize build ."
#         kustomize build .
#   discover:
#     fileName: "kustomization.yaml"
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZaTR5NnVYVUwxaHBWcnRo
            aXdId1Q4dVNCQTdYM1ZSbk5lejZBaWxxYnpRClRtQjJVMUhsQ2tlSGN4T1MxajU0
            NFl5bWkzeDFKU3hhbHlIRVR1QmxXVUkKLS0tIEUvMCt2VndWcDhPdjlQNmw1QnU0
            elJ6b09LRVJXWC9HakpTdDM3S0V6Q0UKcEQ7njLtj6JKPtkMrez6HDz9r3RZnfH4
            Fh1TuKwEENf8XHuZjHFRjNfMu/IRjHcMUHaHUVUVXi5V/LzJC46+6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-19T15:31:44Z"
    mac: ENC[AES256_GCM,data:QyeNYlUAXmh7T2L2G4Dj8HlyD4Swc6qRqzGmd1KwhTnqsfBymHI3VHjIBm8rbBGp8OMMiqyxH40+DqFaUys4PNwJflWmCkO9w52nMxrYtRujQSSYO8wbYzGrvVY47xBhZLvxVMB1WU3wn2TYwq1/3CL1UWHJ4HbEObGPV9Jx718=,iv:8yIeGUl4zMIw51dUCY+jwi+jiuvssvalxJpSYGkT/pQ=,tag:ale54Y3uRPi4DizkEcikag==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token)$
    version: 3.7.1
