apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: local
    namespace: argocd
spec:
    description: Project for local k8s cluster
    sourceRepos:
        - https://github.com/nazmang/k8s.git
        - https://kubernetes-sigs.github.io/external-dns/
    destinations:
        - namespace: '*'
          server: https://kubernetes.default.svc
    clusterResourceWhitelist:
        - group: '*'
          kind: '*'
    namespaceResourceWhitelist:
        - group: '*'
          kind: '*'
    orphanedResources:
        warn: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFL2VtTU1yTlhqcmVKd3BQ
            WnNKa2oxaDdTQWZrLzMzaUdMRUU5TkxyU1NZCmQ3R1A1dlRDOUpxbUtoMFBtdEVw
            UTVaODMwcW4xc3lsdC9OZVk3ZEsrOFEKLS0tIDVFTTB1a0VyYWFoSG1pNHFseDFM
            NEk3MjBOaEY0b1dyQTh5clh3cTdOWVEKPkUEAztqkVlfUX8eGI3kOwfz+Ar9ftEB
            FYIJcEDz4G9EMoQ55IaPDSjB4lxpTg/lDVr5PTFeXfrEReDzkf2ZpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-11T18:30:34Z"
    mac: ENC[AES256_GCM,data:yvzWU+RpGW/BU63YgMkCJfe11CamjxsREKYTHi8O1l9gVCA/eBtND2CgJccthhwDndA4cNJLJ4bu9a5XARDbHown52duySyVwIihhbYcWHw6H0Qw8IKmSU5XNw369/qNvz+rx3v8Rd25IYuSk2hFU/GvK3VtitSLENVBJsTWQqA=,iv:2Ou/8UtCytRx02mY/YNljonlk8RwrFDrb2D3ho2R9Ec=,tag:BTXTF3xm/lWoqO0FWej/Ow==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token)$
    version: 3.7.1
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: apps-root
    namespace: argocd
spec:
    project: local
    source:
        repoURL: https://github.com/nazmang/k8s.git
        targetRevision: HEAD
        path: apps/
    destination:
        server: https://kubernetes.default.svc
        namespace: argocd
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFL2VtTU1yTlhqcmVKd3BQ
            WnNKa2oxaDdTQWZrLzMzaUdMRUU5TkxyU1NZCmQ3R1A1dlRDOUpxbUtoMFBtdEVw
            UTVaODMwcW4xc3lsdC9OZVk3ZEsrOFEKLS0tIDVFTTB1a0VyYWFoSG1pNHFseDFM
            NEk3MjBOaEY0b1dyQTh5clh3cTdOWVEKPkUEAztqkVlfUX8eGI3kOwfz+Ar9ftEB
            FYIJcEDz4G9EMoQ55IaPDSjB4lxpTg/lDVr5PTFeXfrEReDzkf2ZpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-11T18:30:34Z"
    mac: ENC[AES256_GCM,data:yvzWU+RpGW/BU63YgMkCJfe11CamjxsREKYTHi8O1l9gVCA/eBtND2CgJccthhwDndA4cNJLJ4bu9a5XARDbHown52duySyVwIihhbYcWHw6H0Qw8IKmSU5XNw369/qNvz+rx3v8Rd25IYuSk2hFU/GvK3VtitSLENVBJsTWQqA=,iv:2Ou/8UtCytRx02mY/YNljonlk8RwrFDrb2D3ho2R9Ec=,tag:BTXTF3xm/lWoqO0FWej/Ow==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: sops-age-key
    namespace: argocd
type: Opaque
stringData:
    SOPS_AGE_KEY: ENC[AES256_GCM,data:4yikkThJ8tjwYGSYLnIDJjaAhmoEuVhQMgaCs4RU619Z1yj2+d93zl3fpc0KErabbb7soDbvz4X6Raob1EdkwZclnWE3heX3xL4=,iv:T03Rdq/GVAhMhODG0/xkM5kG7vAqEOmlJboEixLXUCo=,tag:kuYxjK41dnmpHa6wJqOmXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFL2VtTU1yTlhqcmVKd3BQ
            WnNKa2oxaDdTQWZrLzMzaUdMRUU5TkxyU1NZCmQ3R1A1dlRDOUpxbUtoMFBtdEVw
            UTVaODMwcW4xc3lsdC9OZVk3ZEsrOFEKLS0tIDVFTTB1a0VyYWFoSG1pNHFseDFM
            NEk3MjBOaEY0b1dyQTh5clh3cTdOWVEKPkUEAztqkVlfUX8eGI3kOwfz+Ar9ftEB
            FYIJcEDz4G9EMoQ55IaPDSjB4lxpTg/lDVr5PTFeXfrEReDzkf2ZpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-11T18:30:34Z"
    mac: ENC[AES256_GCM,data:yvzWU+RpGW/BU63YgMkCJfe11CamjxsREKYTHi8O1l9gVCA/eBtND2CgJccthhwDndA4cNJLJ4bu9a5XARDbHown52duySyVwIihhbYcWHw6H0Qw8IKmSU5XNw369/qNvz+rx3v8Rd25IYuSk2hFU/GvK3VtitSLENVBJsTWQqA=,iv:2Ou/8UtCytRx02mY/YNljonlk8RwrFDrb2D3ho2R9Ec=,tag:BTXTF3xm/lWoqO0FWej/Ow==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token)$
    version: 3.7.1
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: argocd-application-controller-hpa
    namespace: argocd
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: argocd-argo-cd-app-controller
    minReplicas: 1
    maxReplicas: 5
    metrics:
        - type: Resource
          resource:
            name: cpu
            target:
                type: Utilization
                averageUtilization: 70
        - type: Resource
          resource:
            name: memory
            target:
                type: Utilization
                averageUtilization: 60
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: ConfigManagementPlugin
# metadata:
#   name: sops-decrypt
#   namespace: argocd
# spec:
#   version: v1.0
#   init:
#     command: ["/bin/sh", "-c"]
#     args:
#       - |
#         set -euo pipefail
#         echo "[CMP:init] preparing sops binary (v3.10.2)..."
#         VERSION="v3.10.2"
#         ARCH=$(uname -m)
#         case "$ARCH" in
#           x86_64|amd64) ARCH="amd64" ;;
#           aarch64|arm64) ARCH="arm64" ;;
#           armv7l|armv7) ARCH="arm" ;;
#           *) echo "[CMP:init] Unsupported arch: $ARCH"; exit 1 ;;
#         esac
#         OS=$(uname -s | tr '[:upper:]' '[:lower:]') # linux/darwin
#         URL="https://github.com/getsops/sops/releases/download/v${VERSION}/sops-v${VERSION}.${OS}.${ARCH}"
#         echo "[CMP:init] Downloading SOPS from: $URL"
#         # -fS: fail on http error and show errors, -L for redirects
#         curl -fSL -o /tmp/sops "${URL}"
#         chmod +x /tmp/sops
#         /tmp/sops --version || (echo "[CMP:init] sops failed to run"; exit 1)
#         echo "[CMP:init] sops ready at /tmp/sops (v${VERSION})"
#   generate:
#     command: ["/bin/sh", "-c"]
#     args:
#       - |
#         set -euo pipefail
#         echo "[CMP:generate] start"
#         # Prefer system sops if present, otherwise use downloaded /tmp/sops
#         if command -v sops >/dev/null 2>&1 ; then
#           SOPS_BIN=$(command -v sops)
#         elif [ -x /tmp/sops ]; then
#           SOPS_BIN=/tmp/sops
#         else
#           echo "[CMP:generate] sops not found"; exit 1
#         fi
#         echo "[CMP:generate] using sops: ${SOPS_BIN}"
#         # Decrypt all .env.enc -> .env (in the repo/directory)
#         for f in $(find . -type f -name '*.env.enc' 2>/dev/null || true); do
#           out="${f%.enc}"
#           echo "[CMP:generate] decrypting ${f} -> ${out}"
#           "${SOPS_BIN}" --decrypt --output "${out}" "${f}"
#         done
#         # Optional: decrypt argocd.values.enc -> argocd.values.yaml (if used)
#         if [ -f "argocd.values.enc.yaml" ]; then
#           echo "[CMP:generate] decrypting argocd.values.enc.yaml -> argocd.values.yaml"
#           "${SOPS_BIN}" --decrypt --output argocd.values.yaml argocd.values.enc.yaml
#         fi
#         echo "[CMP:generate] running kustomize build ."
#         kustomize build .
#   discover:
#     fileName: "kustomization.yaml"
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFL2VtTU1yTlhqcmVKd3BQ
            WnNKa2oxaDdTQWZrLzMzaUdMRUU5TkxyU1NZCmQ3R1A1dlRDOUpxbUtoMFBtdEVw
            UTVaODMwcW4xc3lsdC9OZVk3ZEsrOFEKLS0tIDVFTTB1a0VyYWFoSG1pNHFseDFM
            NEk3MjBOaEY0b1dyQTh5clh3cTdOWVEKPkUEAztqkVlfUX8eGI3kOwfz+Ar9ftEB
            FYIJcEDz4G9EMoQ55IaPDSjB4lxpTg/lDVr5PTFeXfrEReDzkf2ZpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-11T18:30:34Z"
    mac: ENC[AES256_GCM,data:yvzWU+RpGW/BU63YgMkCJfe11CamjxsREKYTHi8O1l9gVCA/eBtND2CgJccthhwDndA4cNJLJ4bu9a5XARDbHown52duySyVwIihhbYcWHw6H0Qw8IKmSU5XNw369/qNvz+rx3v8Rd25IYuSk2hFU/GvK3VtitSLENVBJsTWQqA=,iv:2Ou/8UtCytRx02mY/YNljonlk8RwrFDrb2D3ho2R9Ec=,tag:BTXTF3xm/lWoqO0FWej/Ow==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token)$
    version: 3.7.1
