apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: local
    namespace: argocd
spec:
    description: Project for local k8s cluster
    sourceRepos:
        - https://github.com/nazmang/k8s.git
        - https://kubernetes-sigs.github.io/external-dns/
    destinations:
        - namespace: '*'
          server: https://kubernetes.default.svc
    clusterResourceWhitelist:
        - group: '*'
          kind: '*'
    namespaceResourceWhitelist:
        - group: '*'
          kind: '*'
    orphanedResources:
        warn: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eU1TdkVoZHYzbVZGcXli
            ejh6Qnc1eUNCcEYzaDJoVkRoR3ExOEpyK0ZrCkFDeUROOVdVek9BK3dRWktrSkRQ
            a2pNRWltR2E0SnZxaUUxMmJBNHNSNTAKLS0tIEp6cE0vc2w5bXZJeXlVcHJPSGlB
            UFROYUNtaGprME5ZRWMvQXJjSGh4QU0KVqaEmKydvx1YqRZGSkD6AKecdwd8beJK
            ZIw4GcxHSJ9+nJv9b0J/wzWm3c77ph3eJt8kwqVlEg+jJ8hU2LOAFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-11T18:45:13Z"
    mac: ENC[AES256_GCM,data:zCnfW4xUh/FO9VsBmhHtx8ubY0pmvDmDdxws48uLisXtpdWpfOkyJvSiRBdUyS0fHACjK95xMOpPNvtszJTQPRztKX/cFGkl5tkOSdJVelaFPE1bPzcMr2+DCbU46+4o6yVJY4CyjkCTply/ciEgD6vWUF6nvoo88j8iZjHj3wM=,iv:rK5T/g66POWEEr91MID9mbTdSflYy/wku4vgkmnTUUU=,tag:xaBdP4OdXTX2GBZqBePyYQ==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token)$
    version: 3.7.1
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: apps-root
    namespace: argocd
spec:
    project: local
    source:
        repoURL: https://github.com/nazmang/k8s.git
        targetRevision: HEAD
        path: apps/
    destination:
        server: https://kubernetes.default.svc
        namespace: argocd
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eU1TdkVoZHYzbVZGcXli
            ejh6Qnc1eUNCcEYzaDJoVkRoR3ExOEpyK0ZrCkFDeUROOVdVek9BK3dRWktrSkRQ
            a2pNRWltR2E0SnZxaUUxMmJBNHNSNTAKLS0tIEp6cE0vc2w5bXZJeXlVcHJPSGlB
            UFROYUNtaGprME5ZRWMvQXJjSGh4QU0KVqaEmKydvx1YqRZGSkD6AKecdwd8beJK
            ZIw4GcxHSJ9+nJv9b0J/wzWm3c77ph3eJt8kwqVlEg+jJ8hU2LOAFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-11T18:45:13Z"
    mac: ENC[AES256_GCM,data:zCnfW4xUh/FO9VsBmhHtx8ubY0pmvDmDdxws48uLisXtpdWpfOkyJvSiRBdUyS0fHACjK95xMOpPNvtszJTQPRztKX/cFGkl5tkOSdJVelaFPE1bPzcMr2+DCbU46+4o6yVJY4CyjkCTply/ciEgD6vWUF6nvoo88j8iZjHj3wM=,iv:rK5T/g66POWEEr91MID9mbTdSflYy/wku4vgkmnTUUU=,tag:xaBdP4OdXTX2GBZqBePyYQ==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: sops-age-key
    namespace: argocd
type: Opaque
stringData:
    SOPS_AGE_KEY: ENC[AES256_GCM,data:3VjweRVrXQT6r2XZyxUl83Osks2U3zxCXkDGcFMZSjMUY9wKoGrROhPhRxrwNhwR60GkyDphP6VszAPXFCewP/x78QTDCAx6nK0=,iv:U3qq6ouikNwWpTL7XpaOPvIRgk3f5PM9HhPKcfrvJsU=,tag:iDAWUS8rA4E3S5bJO/ol6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eU1TdkVoZHYzbVZGcXli
            ejh6Qnc1eUNCcEYzaDJoVkRoR3ExOEpyK0ZrCkFDeUROOVdVek9BK3dRWktrSkRQ
            a2pNRWltR2E0SnZxaUUxMmJBNHNSNTAKLS0tIEp6cE0vc2w5bXZJeXlVcHJPSGlB
            UFROYUNtaGprME5ZRWMvQXJjSGh4QU0KVqaEmKydvx1YqRZGSkD6AKecdwd8beJK
            ZIw4GcxHSJ9+nJv9b0J/wzWm3c77ph3eJt8kwqVlEg+jJ8hU2LOAFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-11T18:45:13Z"
    mac: ENC[AES256_GCM,data:zCnfW4xUh/FO9VsBmhHtx8ubY0pmvDmDdxws48uLisXtpdWpfOkyJvSiRBdUyS0fHACjK95xMOpPNvtszJTQPRztKX/cFGkl5tkOSdJVelaFPE1bPzcMr2+DCbU46+4o6yVJY4CyjkCTply/ciEgD6vWUF6nvoo88j8iZjHj3wM=,iv:rK5T/g66POWEEr91MID9mbTdSflYy/wku4vgkmnTUUU=,tag:xaBdP4OdXTX2GBZqBePyYQ==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token)$
    version: 3.7.1
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: argocd-application-controller-hpa
    namespace: argocd
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: argocd-argo-cd-app-controller
    minReplicas: 1
    maxReplicas: 5
    metrics:
        - type: Resource
          resource:
            name: cpu
            target:
                type: Utilization
                averageUtilization: 70
        - type: Resource
          resource:
            name: memory
            target:
                type: Utilization
                averageUtilization: 90
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: ConfigManagementPlugin
# metadata:
#   name: sops-decrypt
#   namespace: argocd
# spec:
#   version: v1.0
#   init:
#     command: ["/bin/sh", "-c"]
#     args:
#       - |
#         set -euo pipefail
#         echo "[CMP:init] preparing sops binary (v3.10.2)..."
#         VERSION="v3.10.2"
#         ARCH=$(uname -m)
#         case "$ARCH" in
#           x86_64|amd64) ARCH="amd64" ;;
#           aarch64|arm64) ARCH="arm64" ;;
#           armv7l|armv7) ARCH="arm" ;;
#           *) echo "[CMP:init] Unsupported arch: $ARCH"; exit 1 ;;
#         esac
#         OS=$(uname -s | tr '[:upper:]' '[:lower:]') # linux/darwin
#         URL="https://github.com/getsops/sops/releases/download/v${VERSION}/sops-v${VERSION}.${OS}.${ARCH}"
#         echo "[CMP:init] Downloading SOPS from: $URL"
#         # -fS: fail on http error and show errors, -L for redirects
#         curl -fSL -o /tmp/sops "${URL}"
#         chmod +x /tmp/sops
#         /tmp/sops --version || (echo "[CMP:init] sops failed to run"; exit 1)
#         echo "[CMP:init] sops ready at /tmp/sops (v${VERSION})"
#   generate:
#     command: ["/bin/sh", "-c"]
#     args:
#       - |
#         set -euo pipefail
#         echo "[CMP:generate] start"
#         # Prefer system sops if present, otherwise use downloaded /tmp/sops
#         if command -v sops >/dev/null 2>&1 ; then
#           SOPS_BIN=$(command -v sops)
#         elif [ -x /tmp/sops ]; then
#           SOPS_BIN=/tmp/sops
#         else
#           echo "[CMP:generate] sops not found"; exit 1
#         fi
#         echo "[CMP:generate] using sops: ${SOPS_BIN}"
#         # Decrypt all .env.enc -> .env (in the repo/directory)
#         for f in $(find . -type f -name '*.env.enc' 2>/dev/null || true); do
#           out="${f%.enc}"
#           echo "[CMP:generate] decrypting ${f} -> ${out}"
#           "${SOPS_BIN}" --decrypt --output "${out}" "${f}"
#         done
#         # Optional: decrypt argocd.values.enc -> argocd.values.yaml (if used)
#         if [ -f "argocd.values.enc.yaml" ]; then
#           echo "[CMP:generate] decrypting argocd.values.enc.yaml -> argocd.values.yaml"
#           "${SOPS_BIN}" --decrypt --output argocd.values.yaml argocd.values.enc.yaml
#         fi
#         echo "[CMP:generate] running kustomize build ."
#         kustomize build .
#   discover:
#     fileName: "kustomization.yaml"
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eU1TdkVoZHYzbVZGcXli
            ejh6Qnc1eUNCcEYzaDJoVkRoR3ExOEpyK0ZrCkFDeUROOVdVek9BK3dRWktrSkRQ
            a2pNRWltR2E0SnZxaUUxMmJBNHNSNTAKLS0tIEp6cE0vc2w5bXZJeXlVcHJPSGlB
            UFROYUNtaGprME5ZRWMvQXJjSGh4QU0KVqaEmKydvx1YqRZGSkD6AKecdwd8beJK
            ZIw4GcxHSJ9+nJv9b0J/wzWm3c77ph3eJt8kwqVlEg+jJ8hU2LOAFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-11T18:45:13Z"
    mac: ENC[AES256_GCM,data:zCnfW4xUh/FO9VsBmhHtx8ubY0pmvDmDdxws48uLisXtpdWpfOkyJvSiRBdUyS0fHACjK95xMOpPNvtszJTQPRztKX/cFGkl5tkOSdJVelaFPE1bPzcMr2+DCbU46+4o6yVJY4CyjkCTply/ciEgD6vWUF6nvoo88j8iZjHj3wM=,iv:rK5T/g66POWEEr91MID9mbTdSflYy/wku4vgkmnTUUU=,tag:xaBdP4OdXTX2GBZqBePyYQ==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token)$
    version: 3.7.1
