---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: local
  namespace: argocd
spec:
  description: Project for local k8s cluster
  sourceRepos:
    - https://github.com/nazmang/*
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-root
  namespace: argocd
spec:
  project: local
  source:
    repoURL: https://github.com/nazmang/k8s.git
    targetRevision: HEAD
    path: apps/
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
