apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: local
    namespace: argocd
spec:
    description: Project for local k8s cluster
    sourceRepos:
        - https://github.com/nazmang/k8s.git
        - https://kubernetes-sigs.github.io/external-dns/
        - https://aquasecurity.github.io/helm-charts/
        - https://github.com/raoulx24/trivy-operator-dashboard.git
        - https://helm.releases.hashicorp.com
        - https://*.github.io/*
        - https://*.github.com/*
        - https://stakater.github.io/stakater-charts
        - https://cloudhippie.github.io/charts
    destinations:
        - namespace: '*'
          server: https://kubernetes.default.svc
    clusterResourceWhitelist:
        - group: '*'
          kind: '*'
    namespaceResourceWhitelist:
        - group: '*'
          kind: '*'
    orphanedResources:
        warn: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUmJtMVcrOXB2amR4MHdG
            VEM3eWN4ajNjZ3NyODB1Q2tnL2pKa214UlRvCm4yT3FSMTRWRzZnU1ZPY2xQajUz
            VmhBbDJiN1kzcCtmcEVKaGp4WjNzbW8KLS0tIE14QktGcWQxbGMwR25aNU9mVnBr
            SWtMb3J0cFZjQWgyckxlZjhFZTgzSjAKupjZvylmdo7WW02o3Jf8VCXnVPxIVSUH
            oOSCH9iktpgTZRrAArzqyWTQwHdFWUiqVf6xubGVtL0UMTDXXO3PEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-28T15:58:51Z"
    mac: ENC[AES256_GCM,data:dtbTTOcdNhF/I48+q7jiyaSl9qoSy9rOe1Zptg4CQgiNIZp07rgw1LXXNqGi6+d4JY+ijat4B2a3YmmvgOHPFooTcpQ2gNe+VwkkXmdu896lt9KM36G8jJf8CkybtvgPm/mQlylSLV00lti+1+K+2YCq1kWv4KRcw7uBHTpiNj4=,iv:bAhoj6AbAj/ivB72uVMUneyv+lH4bk/8rOddLuj8iiE=,tag:C+Wm9nrlRIGOLaLv/HoL9g==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml)$
    version: 3.7.1
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: apps-root
    namespace: argocd
spec:
    project: local
    source:
        repoURL: https://github.com/nazmang/k8s.git
        targetRevision: HEAD
        path: apps/
    destination:
        server: https://kubernetes.default.svc
        namespace: argocd
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUmJtMVcrOXB2amR4MHdG
            VEM3eWN4ajNjZ3NyODB1Q2tnL2pKa214UlRvCm4yT3FSMTRWRzZnU1ZPY2xQajUz
            VmhBbDJiN1kzcCtmcEVKaGp4WjNzbW8KLS0tIE14QktGcWQxbGMwR25aNU9mVnBr
            SWtMb3J0cFZjQWgyckxlZjhFZTgzSjAKupjZvylmdo7WW02o3Jf8VCXnVPxIVSUH
            oOSCH9iktpgTZRrAArzqyWTQwHdFWUiqVf6xubGVtL0UMTDXXO3PEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-28T15:58:51Z"
    mac: ENC[AES256_GCM,data:dtbTTOcdNhF/I48+q7jiyaSl9qoSy9rOe1Zptg4CQgiNIZp07rgw1LXXNqGi6+d4JY+ijat4B2a3YmmvgOHPFooTcpQ2gNe+VwkkXmdu896lt9KM36G8jJf8CkybtvgPm/mQlylSLV00lti+1+K+2YCq1kWv4KRcw7uBHTpiNj4=,iv:bAhoj6AbAj/ivB72uVMUneyv+lH4bk/8rOddLuj8iiE=,tag:C+Wm9nrlRIGOLaLv/HoL9g==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: sops-age-key
    namespace: argocd
type: Opaque
stringData:
    SOPS_AGE_KEY: ENC[AES256_GCM,data:J+A/ESi6zu3brLn1tJaEzAXJ5nTIwAtnSyD9df4Ir6bETwSiLKW1FY/jcpHhaI5L89iLEbA9JXUWcFQv373Hs7ns6H1gByqGw+M=,iv:Eb+Pqb6qEyLirk/LpSeFN091R751bHQV2hLIAPhW7Y0=,tag:dxaK5PS6qNGymZ4h7SVY5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUmJtMVcrOXB2amR4MHdG
            VEM3eWN4ajNjZ3NyODB1Q2tnL2pKa214UlRvCm4yT3FSMTRWRzZnU1ZPY2xQajUz
            VmhBbDJiN1kzcCtmcEVKaGp4WjNzbW8KLS0tIE14QktGcWQxbGMwR25aNU9mVnBr
            SWtMb3J0cFZjQWgyckxlZjhFZTgzSjAKupjZvylmdo7WW02o3Jf8VCXnVPxIVSUH
            oOSCH9iktpgTZRrAArzqyWTQwHdFWUiqVf6xubGVtL0UMTDXXO3PEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-28T15:58:51Z"
    mac: ENC[AES256_GCM,data:dtbTTOcdNhF/I48+q7jiyaSl9qoSy9rOe1Zptg4CQgiNIZp07rgw1LXXNqGi6+d4JY+ijat4B2a3YmmvgOHPFooTcpQ2gNe+VwkkXmdu896lt9KM36G8jJf8CkybtvgPm/mQlylSLV00lti+1+K+2YCq1kWv4KRcw7uBHTpiNj4=,iv:bAhoj6AbAj/ivB72uVMUneyv+lH4bk/8rOddLuj8iiE=,tag:C+Wm9nrlRIGOLaLv/HoL9g==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml)$
    version: 3.7.1
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: argocd-vault-plugin
    namespace: argocd
data:
    configManagementPlugins.yaml: |
        apiVersion: argoproj.io/v1alpha1
        kind: ConfigManagementPlugin
        metadata:
          name: argocd-vault-plugin
          namespace: argocd
        spec:
          version: v1.0
          init:
            command: ["/bin/sh", "-c"]
            args: ["echo 'Initializing argocd-vault-plugin'"]
          generate:
            command: ["/bin/sh", "-c"]
            args: ["/usr/local/bin/sops -d $VALUES_FILE"]
          discover:
            find:
              command: ["sh", "-c", "find . -maxdepth 1 -type f -name '*.enc.yaml' -print -quit"]
# ---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#     name: argocd-application-controller-hpa
#     namespace: argocd
# spec:
#     scaleTargetRef:
#         apiVersion: apps/v1
#         kind: Deployment
#         name: argocd-argo-cd-app-controller
#     minReplicas: 1
#     maxReplicas: 3
#     metrics:
#         - type: Resource
#           resource:
#             name: cpu
#             target:
#                 type: Utilization
#                 averageUtilization: 70
#         - type: Resource
#           resource:
#             name: memory
#             target:
#                 type: Utilization
#                 averageUtilization: 95
# ---
# apiVersion: autoscaling.k8s.io/v1
# kind: VerticalPodAutoscaler
# metadata:
#     name: argocd-argo-cd-repo-server-vpa
#     namespace: argocd
# spec:
#     targetRef:
#         apiVersion: apps/v1
#         kind: Deployment
#         name: argocd-argo-cd-repo-server
#     updatePolicy:
#         # Auto | Off | Initial
#         updateMode: Auto
#     resourcePolicy:
#         containerPolicies:
#             - containerName: '*'
#               minAllowed:
#                 cpu: 100m
#                 memory: 256Mi
#               maxAllowed:
#                 cpu: "1"
#                 memory: 756Mi
#               controlledResources:
#                 - cpu
#                 - memory
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUmJtMVcrOXB2amR4MHdG
            VEM3eWN4ajNjZ3NyODB1Q2tnL2pKa214UlRvCm4yT3FSMTRWRzZnU1ZPY2xQajUz
            VmhBbDJiN1kzcCtmcEVKaGp4WjNzbW8KLS0tIE14QktGcWQxbGMwR25aNU9mVnBr
            SWtMb3J0cFZjQWgyckxlZjhFZTgzSjAKupjZvylmdo7WW02o3Jf8VCXnVPxIVSUH
            oOSCH9iktpgTZRrAArzqyWTQwHdFWUiqVf6xubGVtL0UMTDXXO3PEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-28T15:58:51Z"
    mac: ENC[AES256_GCM,data:dtbTTOcdNhF/I48+q7jiyaSl9qoSy9rOe1Zptg4CQgiNIZp07rgw1LXXNqGi6+d4JY+ijat4B2a3YmmvgOHPFooTcpQ2gNe+VwkkXmdu896lt9KM36G8jJf8CkybtvgPm/mQlylSLV00lti+1+K+2YCq1kWv4KRcw7uBHTpiNj4=,iv:bAhoj6AbAj/ivB72uVMUneyv+lH4bk/8rOddLuj8iiE=,tag:C+Wm9nrlRIGOLaLv/HoL9g==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml)$
    version: 3.7.1
