apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: local
    namespace: argocd
spec:
    description: Project for local k8s cluster
    sourceRepos:
        - https://github.com/nazmang/k8s.git
        - https://kubernetes-sigs.github.io/external-dns/
        - https://aquasecurity.github.io/helm-charts/
        - https://github.com/raoulx24/trivy-operator-dashboard.git
        - https://helm.releases.hashicorp.com
        - https://*.github.io/*
        - https://*.github.com/*
        - https://stakater.github.io/stakater-charts
        - https://cloudhippie.github.io/charts
    destinations:
        - namespace: '*'
          server: https://kubernetes.default.svc
    clusterResourceWhitelist:
        - group: '*'
          kind: '*'
    namespaceResourceWhitelist:
        - group: '*'
          kind: '*'
    orphanedResources:
        warn: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQnFEL1kzWEdYRG1vM0cr
            YWw5a0N4azFvbmhXOVBxQWVDa0VsK2p0L0Y0CmdSdmluNWgzVHRhQU1DU1hTUk9E
            VkxydnVidk9tVkFVY3JOL01RUTh5SmMKLS0tIExoajBmODl6R09TazgxNG94YWpH
            QnE1R0VZajNLb3EwbFo2T3NYbzN6NDgK7zWazMajIL0Uvk1dhkOcUDEq/tBkPvKE
            /XkP25HaCx6rsG7Xas5gavO98QhVrJIpPcrjn6N5o1x4E05X8L2zOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-28T17:57:57Z"
    mac: ENC[AES256_GCM,data:Mx2AZDxNG5q4wHpNjWgKcGW6D0xEpckZyKC5Q5OeWXY7D2vxYjwh2tOaMJ4hAZplHJamhiXieqOsN1OCzKkZX2upKT8c+lq4QP7pnIgDGTxvuTO5fK6DT0FWbK5Z+KsMlfE5bZmtxxqS4G7luSO3D44Iaa8mEIvUT4ymPei5s/I=,iv:9gEdQ9Lvnhb2hcu+lsXXqNiYJDQkcpbzYUJ59B1WKoo=,tag:DW2QTQi6AdlUE3NBXj5Y5Q==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml)$
    version: 3.7.1
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: apps-root
    namespace: argocd
spec:
    project: local
    source:
        repoURL: https://github.com/nazmang/k8s.git
        targetRevision: HEAD
        path: apps/
    destination:
        server: https://kubernetes.default.svc
        namespace: argocd
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQnFEL1kzWEdYRG1vM0cr
            YWw5a0N4azFvbmhXOVBxQWVDa0VsK2p0L0Y0CmdSdmluNWgzVHRhQU1DU1hTUk9E
            VkxydnVidk9tVkFVY3JOL01RUTh5SmMKLS0tIExoajBmODl6R09TazgxNG94YWpH
            QnE1R0VZajNLb3EwbFo2T3NYbzN6NDgK7zWazMajIL0Uvk1dhkOcUDEq/tBkPvKE
            /XkP25HaCx6rsG7Xas5gavO98QhVrJIpPcrjn6N5o1x4E05X8L2zOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-28T17:57:57Z"
    mac: ENC[AES256_GCM,data:Mx2AZDxNG5q4wHpNjWgKcGW6D0xEpckZyKC5Q5OeWXY7D2vxYjwh2tOaMJ4hAZplHJamhiXieqOsN1OCzKkZX2upKT8c+lq4QP7pnIgDGTxvuTO5fK6DT0FWbK5Z+KsMlfE5bZmtxxqS4G7luSO3D44Iaa8mEIvUT4ymPei5s/I=,iv:9gEdQ9Lvnhb2hcu+lsXXqNiYJDQkcpbzYUJ59B1WKoo=,tag:DW2QTQi6AdlUE3NBXj5Y5Q==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: sops-age-key
    namespace: argocd
type: Opaque
stringData:
    SOPS_AGE_KEY: ENC[AES256_GCM,data:rbMtKcrxYgaFM0l96MO7B37LnDaZtOf9IokFjYw9rthOrTLA4QrwBpk1ljNiBE9+xBud2lDThT8VpVH23KGOnzyJLi+aJBzrY0E=,iv:oXewZ4C6OKGUoAqbgFknW0tZkR78ENvwUb4kGLvCCDE=,tag:sesXIL02agS5bvAzJV9ASA==,type:str]
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#     name: argocd-vault-plugin
#     namespace: argocd
# data:
#     configManagementPlugins.yaml: |
#         apiVersion: argoproj.io/v1alpha1
#         kind: ConfigManagementPlugin
#         metadata:
#           name: argocd-vault-plugin
#           namespace: argocd
#         spec:
#           version: v1.0
#           init:
#             command: ["/bin/sh", "-c"]
#             args: ["echo 'Initializing argocd-vault-plugin'"]
#           generate:
#             command: ["/bin/sh", "-c"]
#             args: ["/usr/local/bin/sops -d $VALUES_FILE"]
#           discover:
#             find:
#               command: ["sh", "-c", "find . -maxdepth 1 -type f -name '*.enc.yaml' -print -quit"]
# ---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#     name: argocd-application-controller-hpa
#     namespace: argocd
# spec:
#     scaleTargetRef:
#         apiVersion: apps/v1
#         kind: Deployment
#         name: argocd-argo-cd-app-controller
#     minReplicas: 1
#     maxReplicas: 3
#     metrics:
#         - type: Resource
#           resource:
#             name: cpu
#             target:
#                 type: Utilization
#                 averageUtilization: 70
#         - type: Resource
#           resource:
#             name: memory
#             target:
#                 type: Utilization
#                 averageUtilization: 95
# ---
# apiVersion: autoscaling.k8s.io/v1
# kind: VerticalPodAutoscaler
# metadata:
#     name: argocd-argo-cd-repo-server-vpa
#     namespace: argocd
# spec:
#     targetRef:
#         apiVersion: apps/v1
#         kind: Deployment
#         name: argocd-argo-cd-repo-server
#     updatePolicy:
#         # Auto | Off | Initial
#         updateMode: Auto
#     resourcePolicy:
#         containerPolicies:
#             - containerName: '*'
#               minAllowed:
#                 cpu: 100m
#                 memory: 256Mi
#               maxAllowed:
#                 cpu: "1"
#                 memory: 756Mi
#               controlledResources:
#                 - cpu
#                 - memory
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQnFEL1kzWEdYRG1vM0cr
            YWw5a0N4azFvbmhXOVBxQWVDa0VsK2p0L0Y0CmdSdmluNWgzVHRhQU1DU1hTUk9E
            VkxydnVidk9tVkFVY3JOL01RUTh5SmMKLS0tIExoajBmODl6R09TazgxNG94YWpH
            QnE1R0VZajNLb3EwbFo2T3NYbzN6NDgK7zWazMajIL0Uvk1dhkOcUDEq/tBkPvKE
            /XkP25HaCx6rsG7Xas5gavO98QhVrJIpPcrjn6N5o1x4E05X8L2zOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-28T17:57:57Z"
    mac: ENC[AES256_GCM,data:Mx2AZDxNG5q4wHpNjWgKcGW6D0xEpckZyKC5Q5OeWXY7D2vxYjwh2tOaMJ4hAZplHJamhiXieqOsN1OCzKkZX2upKT8c+lq4QP7pnIgDGTxvuTO5fK6DT0FWbK5Z+KsMlfE5bZmtxxqS4G7luSO3D44Iaa8mEIvUT4ymPei5s/I=,iv:9gEdQ9Lvnhb2hcu+lsXXqNiYJDQkcpbzYUJ59B1WKoo=,tag:DW2QTQi6AdlUE3NBXj5Y5Q==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml)$
    version: 3.7.1
