apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: local
    namespace: argocd
spec:
    description: Project for local k8s cluster
    sourceRepos:
        - https://github.com/nazmang/k8s.git
        - https://kubernetes-sigs.github.io/external-dns/
        - https://aquasecurity.github.io/helm-charts/
        - https://github.com/raoulx24/trivy-operator-dashboard.git
        - https://helm.releases.hashicorp.com
        - https://*.github.io/*
        - https://*.github.com/*
        - https://stakater.github.io/stakater-charts
        - https://cloudhippie.github.io/charts
    destinations:
        - namespace: '*'
          server: https://kubernetes.default.svc
    clusterResourceWhitelist:
        - group: '*'
          kind: '*'
    namespaceResourceWhitelist:
        - group: '*'
          kind: '*'
    orphanedResources:
        warn: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdVkzVHd5VitseGgyT0w2
            MXJjWVNtNTIwK0RQMThIa0xiVTh5NUxuWmw0CjEwYjVSYytxOWpMcW9CSGx6UVk5
            bm0yckk4N2pqekZ4NFh1aGR3d0paNGsKLS0tIGIzdUxRWUdjUTBzQmRLYzAzNlkx
            MTlWOUxjQ3ZZSW5rcFJXaTlvcGxuLzgKY2omrFfl7cBTfh2C5iF7SQHHJjij9EOb
            aoWRBvCqHgdbLVX/driHLSw+WHxYawHtNPCbLQ9wG8HC04N/8yfjOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-27T16:55:46Z"
    mac: ENC[AES256_GCM,data:yqSblDTeMUNWk3OT3nVlxccOgzwBUDPQrG29nrsUWr6zOz3OJPpqLQqvb/TacLdoghXGlUaBsL4bRIQSvVJVrUE6mhf68gO64YhZ4UiDYQGGrSB/MkG5xUT61WiCRcUOi44+JkoqesAGLyT0GpQ2TdA3fSDYnFyzEph7nu0hsLQ=,iv:kxg4y4/VOzIVoHxt2k0iZkXVTft4ryjQfl1QhNCO0DQ=,tag:G7rvOFkjiRZJGsjgn4w1Gw==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml)$
    version: 3.7.1
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: apps-root
    namespace: argocd
spec:
    project: local
    source:
        repoURL: https://github.com/nazmang/k8s.git
        targetRevision: HEAD
        path: apps/
    destination:
        server: https://kubernetes.default.svc
        namespace: argocd
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdVkzVHd5VitseGgyT0w2
            MXJjWVNtNTIwK0RQMThIa0xiVTh5NUxuWmw0CjEwYjVSYytxOWpMcW9CSGx6UVk5
            bm0yckk4N2pqekZ4NFh1aGR3d0paNGsKLS0tIGIzdUxRWUdjUTBzQmRLYzAzNlkx
            MTlWOUxjQ3ZZSW5rcFJXaTlvcGxuLzgKY2omrFfl7cBTfh2C5iF7SQHHJjij9EOb
            aoWRBvCqHgdbLVX/driHLSw+WHxYawHtNPCbLQ9wG8HC04N/8yfjOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-27T16:55:46Z"
    mac: ENC[AES256_GCM,data:yqSblDTeMUNWk3OT3nVlxccOgzwBUDPQrG29nrsUWr6zOz3OJPpqLQqvb/TacLdoghXGlUaBsL4bRIQSvVJVrUE6mhf68gO64YhZ4UiDYQGGrSB/MkG5xUT61WiCRcUOi44+JkoqesAGLyT0GpQ2TdA3fSDYnFyzEph7nu0hsLQ=,iv:kxg4y4/VOzIVoHxt2k0iZkXVTft4ryjQfl1QhNCO0DQ=,tag:G7rvOFkjiRZJGsjgn4w1Gw==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: sops-age-key
    namespace: argocd
type: Opaque
stringData:
    SOPS_AGE_KEY: ENC[AES256_GCM,data:d8nfcRihCAyYDAakUk9W1zgXmckges4yNK+IFE68l7xFNz+DTOlSV7cnylKKM8gf8TYgfZ0y+IZsEbqFqjT2ZEQo4NrB8jEcTjA=,iv:xk+VUYJkyzizxvknM7DlKlB1sb2vgaJc/eWRSvdteTI=,tag:/MI7YqdsOl19wMQaIk9sjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdVkzVHd5VitseGgyT0w2
            MXJjWVNtNTIwK0RQMThIa0xiVTh5NUxuWmw0CjEwYjVSYytxOWpMcW9CSGx6UVk5
            bm0yckk4N2pqekZ4NFh1aGR3d0paNGsKLS0tIGIzdUxRWUdjUTBzQmRLYzAzNlkx
            MTlWOUxjQ3ZZSW5rcFJXaTlvcGxuLzgKY2omrFfl7cBTfh2C5iF7SQHHJjij9EOb
            aoWRBvCqHgdbLVX/driHLSw+WHxYawHtNPCbLQ9wG8HC04N/8yfjOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-27T16:55:46Z"
    mac: ENC[AES256_GCM,data:yqSblDTeMUNWk3OT3nVlxccOgzwBUDPQrG29nrsUWr6zOz3OJPpqLQqvb/TacLdoghXGlUaBsL4bRIQSvVJVrUE6mhf68gO64YhZ4UiDYQGGrSB/MkG5xUT61WiCRcUOi44+JkoqesAGLyT0GpQ2TdA3fSDYnFyzEph7nu0hsLQ=,iv:kxg4y4/VOzIVoHxt2k0iZkXVTft4ryjQfl1QhNCO0DQ=,tag:G7rvOFkjiRZJGsjgn4w1Gw==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml)$
    version: 3.7.1
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: argocd-application-controller-hpa
    namespace: argocd
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: argocd-argo-cd-app-controller
    minReplicas: 1
    maxReplicas: 3
    metrics:
        - type: Resource
          resource:
            name: cpu
            target:
                type: Utilization
                averageUtilization: 70
        - type: Resource
          resource:
            name: memory
            target:
                type: Utilization
                averageUtilization: 95
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdVkzVHd5VitseGgyT0w2
            MXJjWVNtNTIwK0RQMThIa0xiVTh5NUxuWmw0CjEwYjVSYytxOWpMcW9CSGx6UVk5
            bm0yckk4N2pqekZ4NFh1aGR3d0paNGsKLS0tIGIzdUxRWUdjUTBzQmRLYzAzNlkx
            MTlWOUxjQ3ZZSW5rcFJXaTlvcGxuLzgKY2omrFfl7cBTfh2C5iF7SQHHJjij9EOb
            aoWRBvCqHgdbLVX/driHLSw+WHxYawHtNPCbLQ9wG8HC04N/8yfjOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-27T16:55:46Z"
    mac: ENC[AES256_GCM,data:yqSblDTeMUNWk3OT3nVlxccOgzwBUDPQrG29nrsUWr6zOz3OJPpqLQqvb/TacLdoghXGlUaBsL4bRIQSvVJVrUE6mhf68gO64YhZ4UiDYQGGrSB/MkG5xUT61WiCRcUOi44+JkoqesAGLyT0GpQ2TdA3fSDYnFyzEph7nu0hsLQ=,iv:kxg4y4/VOzIVoHxt2k0iZkXVTft4ryjQfl1QhNCO0DQ=,tag:G7rvOFkjiRZJGsjgn4w1Gw==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml)$
    version: 3.7.1
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
    name: argocd-argo-cd-repo-server-vpa
    namespace: argocd
spec:
    targetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: argocd-argo-cd-repo-server
    updatePolicy:
        # Auto | Off | Initial
        updateMode: Auto
    resourcePolicy:
        containerPolicies:
            - containerName: '*'
              minAllowed:
                cpu: 100m
                memory: 256Mi
              maxAllowed:
                cpu: "1"
                memory: 756Mi
              controlledResources:
                - cpu
                - memory
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdVkzVHd5VitseGgyT0w2
            MXJjWVNtNTIwK0RQMThIa0xiVTh5NUxuWmw0CjEwYjVSYytxOWpMcW9CSGx6UVk5
            bm0yckk4N2pqekZ4NFh1aGR3d0paNGsKLS0tIGIzdUxRWUdjUTBzQmRLYzAzNlkx
            MTlWOUxjQ3ZZSW5rcFJXaTlvcGxuLzgKY2omrFfl7cBTfh2C5iF7SQHHJjij9EOb
            aoWRBvCqHgdbLVX/driHLSw+WHxYawHtNPCbLQ9wG8HC04N/8yfjOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-27T16:55:46Z"
    mac: ENC[AES256_GCM,data:yqSblDTeMUNWk3OT3nVlxccOgzwBUDPQrG29nrsUWr6zOz3OJPpqLQqvb/TacLdoghXGlUaBsL4bRIQSvVJVrUE6mhf68gO64YhZ4UiDYQGGrSB/MkG5xUT61WiCRcUOi44+JkoqesAGLyT0GpQ2TdA3fSDYnFyzEph7nu0hsLQ=,iv:kxg4y4/VOzIVoHxt2k0iZkXVTft4ryjQfl1QhNCO0DQ=,tag:G7rvOFkjiRZJGsjgn4w1Gw==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml)$
    version: 3.7.1
