# -- List of extra volumes
extraVolumes: []
# - name: extra
#   emptyDir: {}
# -- List of extra volume mounts
extraVolumeMounts: []
# - name: extra
#   mountPath: /usr/local/share
#   readOnly: true
service:
    # -- Type of the service
    type: ClusterIP
    # -- (int) Port of the service
    port: 3000
    # -- (int) Internal port of the service
    internalPort: 3000
    # -- Additional annotations for the service
    annotations: {}
    # -- Additional labels for the service
    labels: {}
ingress:
    # -- Enable ingress
    enabled: true
    # -- (string) Class name for the ingress resource
    className: nginx
    # -- Host definition for ingress
    hosts:
        - host: semaphore.comintern.local
          paths:
            - path: /
              pathType: Prefix
    # -- Optional TLS configuration for ingress
    tls:
        - hosts:
            # Host for TLS termination.
            - semaphore.comintern.local
          # Secret containing TLS certificate for ingress.
          secretName: semaphore-ingress-tls
    # -- Additional annotations for the ingress
    annotations: {}
    # -- Additional labels for the ingress
    labels: {}
persistence:
    # -- Enable persistence for workdir
    enabled: true
    # -- Size for boltdb volume
    size: 10G
    # -- Storage class used for workdir volume
    storageClass: nfs-client
    # -- Access modes used for workdir volume
    accessModes:
        - ReadWriteOnce
    # -- Name of an already existing claim
    existingClaim: null
secrets:
    # -- Cookie hash secret, generated if not present
    cookieHash: null
    # -- Key used within secret for cookieHash
    cookieHashKey: cookieHash
    # -- Cookie encryption secret, generated if not present
    cookieEncryption: null
    # -- Key used within secret for cookieEncryption
    cookieEncryptionKey: cookieEncryption
    # -- Access key encryption secret, generated if not present
    accesskeyEncryption: null
    # -- Key used within secret for accesskeyEncryption
    accesskeyEncryptionKey: accesskeyEncryption
    # -- Existing secret to use for secrets
    existingSecret: null
general:
    # -- Host to access Semaphore
    host: null
    # -- Use Git client implementation
    gitClient: cmd_git
    # -- Working directory for Semaphore
    tmpPath: /tmp/semaphore
    # -- Maximum parallel tasks
    maxParallelTasks: 0
    # -- Disable password login
    passwordLoginDisable: ENC[AES256_GCM,data:D4dffHU=,iv:HMVx3Sz6/WhaCI3qmw4R7ETN8bESZ6PAuGMl6YGVVOM=,tag:MdCTBeU/+xjpGWXbSTUaHA==,type:bool]
    # -- Allow non-admins to create projects
    nonAdminCanCreateProject: false
    # -- Enable usage of remote runners
    useRemoteRunner: false
    # -- Path to SSH config
    sshConfigPath: ~/.ssh/config
    # -- Additional Python packages
    additionalPythonPackages: []
database:
    # -- Type of database backend
    type: bolt
    # -- Read username from secret
    usernameFromSecret: ENC[AES256_GCM,data:dU5vpQ==,iv:4uoJPWA34Vuz++mWp4Yk08+/tGlQ6Du+/oHy3042jaI=,tag:u4WPh/UPlKM/mHLaRENBGQ==,type:bool]
    # -- Username for database
    username: semaphore
    # -- Key used within secret for username
    usernameKey: username
    # -- Password for database
    password: ENC[AES256_GCM,data:gEZ8n6/AKnCa0jEki24Tw1uw,iv:7A/Au1HFwUGiN2MqilUYi7nCnBQrgnAwax0ABKD2u34=,tag:I/n5cdwqwFh5Su0FpMjPSw==,type:str]
    # -- Key used within secret for password
    passwordKey: ENC[AES256_GCM,data:TJ93M7FdCE0=,iv:4j8CKslxzQfciTE8cddoU/CFqdn3n+eBWYw/2ZUbOrc=,tag:VS66+UlpXbsxVHgUdtXHpg==,type:str]
    # -- Existing secret to use for credentials
    existingSecret: null
    # -- Host for database connection
    host: null
    # -- Port for database connection
    port: null
    # -- Name of the used database
    name: semaphore
    # -- Options for database connection
    options: {}
    # -- Path for the boltdb
    path: /var/lib/semaphore/database.boltdb
    persistence:
        # -- Enable persistence for boltdb
        enabled: true
        # -- Size for boltdb volume
        size: 5G
        # -- Storage class used for boltdb volume
        storageClass: nfs-client
        # -- Access modes used for boltdb volume
        accessModes:
            - ReadWriteOnce
        # -- Name of an already existing claim
        existingClaim: null
ldap:
    # -- Enable LDAP authentication
    enable: false
    # -- Address of LDAP server
    server: null
    # -- Enable TLS connection to LDAP
    needtls: false
    # Search DN for LDAP
    searchdn: null
    # -- Search filter for LDAP
    filter: null
    # -- BindDN for LDAP authentication
    binddn: null
    # -- Key used within secret for username
    binddnKey: username
    # -- Password for LDAP authentication
    password: null
    # -- Key used within secret for username
    passwordKey: ENC[AES256_GCM,data:EaD889bIsgw=,iv:49I6R3BZG5tfeF+44tJWNdIPmcyK93pReXVWdOi6Hb8=,tag:sD+DD5+XW1XjJgbQ2Qyc8A==,type:str]
    # -- Existing secret to use for ldap
    existingSecret: null
    # -- Mapping for LDAP attributes
    mappings:
        dn: dn
        mail: mail
        uid: uid
        cn: cn
oidc:
    # -- Enable oidc authentication
    enable: false
    # -- Dictionary of oidc providers
    providers: {}
email:
    #ENC[AES256_GCM,data:QgfuTiTGUtxLdBg2IV7LdeI+OxURzLbo9Q==,iv:ssqU1B+omuFsMRMItOu4jzevvqsJKBdBhhem5AfYW3A=,tag:29MOOZppznFZyw5EbVmHvw==,type:comment]
    alert: ENC[AES256_GCM,data:PJEyB/w=,iv:vJEiTr0OX+q7J5jx6WRUiikHweIWg1ZanVt88yd/zcE=,tag:KafT6KoeGLDthBFwVsDsGA==,type:bool]
    #ENC[AES256_GCM,data:5b7BIe9C1Kj8RfWh9ErN23CoKZhTXBnZLx9upUs=,iv:LVobkEJqJiqJMUzW44XpS8/6pGCykhZJYby/WWeOZxc=,tag:FBARZJcpDm4d8Swvny0Atw==,type:comment]
    sender: null
    #ENC[AES256_GCM,data:fEcqmRSlFKQf4DJ0AFJq6b01GL2EenQxYCTE,iv:ZbjdxK/EKKjZH2geKrNPCccFsWK8oZyDYVVZPAirT3o=,tag:C+O1ihiErYsb5FUXzxl7eA==,type:comment]
    host: null
    #ENC[AES256_GCM,data:Wir0d13xolTRyWwxyXn0kcYL1wc7qdFtmV63,iv:t8G2B6LmIzcGfn6Bfi9BF/6d9/pryqhqaMYBYMAEvIQ=,tag:i9Z5hoqhrTsa6JyKBHcJWQ==,type:comment]
    port: null
    #ENC[AES256_GCM,data:3pxELY4eYnElwnUiTVjAdzl21TWaqXKOfxcK9n9/,iv:G7HZSmr4nIi2a8tChMCu7TaQm25WLG7Izh1u4xMLwlM=,tag:30ZkVT3O7aGeWv151amREA==,type:comment]
    secure: ENC[AES256_GCM,data:3BRSbSg=,iv:wwszywz+3jabFV0QGiXLzf/2kth8U39BpFmZDPl+frg=,tag:GGl2d2h4KZOu+3rrCUyx8Q==,type:bool]
    #ENC[AES256_GCM,data:A3uKTyS/wvLQUHdqzrh4pDbPt1wgQcoK0EA3CA==,iv:Yy+4YUnEmz23CV6a9jEUKUBDOQAyc6MDbR+CgR5l6Cs=,tag:pfm0lhmDJsg6xshj+2M+Xg==,type:comment]
    username: null
    #ENC[AES256_GCM,data:NBZhu8/P4DlzVCMUeKDqjsdbY+xB5kresJ0rNK6DWms7fzSQ7Qm1,iv:BSGKQVz5cT7Kat1dvxQqLH6vkgQtBKMolwXcQYUH4vU=,tag:ZZyMzO8AoG87Wti944dm5w==,type:comment]
    usernameKey: ENC[AES256_GCM,data:FcpkHs3VAFc=,iv:M7ZKmTKC7h4/XadasJcqEgK8Cj16oJ18g7SD+Tftomo=,tag:2cBTY2/+Abp8IqmEri8pvQ==,type:str]
    #ENC[AES256_GCM,data:WFlG6gItG+mQYjG49Ftaxo0ycgn+ysJsPYVOFA==,iv:Uw6jG/z6F1TxWziTMpM7RA1+bgd1Z6JiY1WRlCsSLUc=,tag:aJ/7yJ0VuEYUD7/TlplP0Q==,type:comment]
    password: null
    #ENC[AES256_GCM,data:oI9TZYmO6VIEJ1eYa+YLNk/0j4ApBIGlBTPkLkbvsgrdn3FYty+a,iv:Ose32kTZ8LbLERZWus67KhyHR61ZfZslWOZsAKiyPho=,tag:nCZ3RfgrTrNCXmp0sVp8lA==,type:comment]
    passwordKey: ENC[AES256_GCM,data:411+i9zTsN4=,iv:NiesMG1mw3sE2f7+dPq1vf/pzkhghLU7hEtUFtolbgQ=,tag:Xfu6Ua+2QpfbrwafZFa3kQ==,type:str]
    #ENC[AES256_GCM,data:G6ej6E8yw+EfSUKs3JdEoZFWXzHnn8eVD1loxyoyHYZ9oLte,iv:itEO7GAo5+7X731SLXIJ0AsWE5c/+4V0xDqUhqlC5W4=,tag:+Pw1SpVhTYvWrhirsEnNzw==,type:comment]
    existingSecret: null
telegram:
    # -- Enable telegram alerting
    alert: false
    # -- Chat used for telegram
    chat: null
    # -- Key used within secret for chat
    chatKey: chat
    # -- Token used for telegram
    token: null
    # -- Key used within secret for token
    tokenKey: token
    # -- Existing secret to use for telegram
    existingSecret: null
slack:
    # -- Enable slack alerting
    alert: false
    # -- URL used for slack
    url: null
    # -- Key used within secret for url
    urlKey: url
    # -- Existing secret to use for slack
    existingSecret: null
runner:
    # -- Runner registration token
    token: null
    # -- Key used within secret for token
    tokenKey: token
    # -- Existing secret to use for runner
    existingSecret: null
billing:
    # -- Enable billing
    enabled: false
admin:
    # -- Create an local admin user
    create: false
    # -- Fullname for local admin
    fullname: Admin
    # -- Key used within secret for fullname
    fullnameKey: fullname
    # -- Username for local admin
    username: admin
    # -- Key used within secret for username
    usernameKey: username
    # -- Password for local admin
    password: ENC[AES256_GCM,data:wcf+Eec=,iv:R6H9XP29VjEefuDfs0etO0GlSEMF6a7B4MWkEBoh4pg=,tag:15sLUHgf2SIExEkjp+el8A==,type:str]
    # -- Key used within secret for password
    passwordKey: ENC[AES256_GCM,data:KjAIiw5nyWg=,iv:hxG/Trsp4oU+YR9i5mZ+jbkRnUsFvxWq6YfgssJfJPM=,tag:KOkgzPUY0sUdQGMhtk35ug==,type:str]
    # -- Email for local admin
    email: ENC[AES256_GCM,data:ZSQl06Pi8WwzlaH7j1Qiuou8087Z,iv:LYRckFtrPZZaJfTOTriLsT+gL6qtmY7LZaqYMGd8rH8=,tag:zYRhzVxxLYY/LQTKcBW9og==,type:str]
    # -- Key used within secret for email
    emailKey: email
    # -- Existing secret to use for admin
    existingSecret: null
# -- Resources for the deployment
resources:
    limits: {}
    requests:
        cpu: 100m
        memory: 64Mi
# -- Node selector for the deployment
nodeSelector: {}
# -- Affinity for the deployment
affinity: {}
# -- Tolerations for the deployment
tolerations: []
# -- List of environment variables from existing secrets
envFromSecrets: []
# -- List of environment variables from existing configmaps
envFromConfigMaps: []
# -- Extra environment variables from mapping
extraEnvVariables: {}
# -- Extra environment variables from secrets
extraEnvSecrets: {}
mariadb:
    # -- Enable mariadb dependency
    enabled: false
    # -- Override fullname of mariadb dependency
    fullnameOverride: mariadb
    auth:
        # -- Database created for semaphore
        database: semaphore
        # -- Username for semaphore database
        username: semaphore
        # -- Password for semaphore database
        password: null
        # -- Password for mariadb admin user
        rootPassword: null
postgres:
    # -- Enable postgres dependency
    enabled: false
    # -- Override fullname of postgres dependency
    fullnameOverride: postgres
    auth:
        # -- Database created for semaphore
        database: semaphore
        # -- Username for semaphore database
        username: semaphore
        # -- Password for semaphore database
        password: null
        # -- Password for postgres admin user
        postgresPassword: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzb08zOUNQVXlGci9xaFNv
            YU0vRmNpMkxxd0MzWGlkTlFyaEhDVlg5T0VRCmRpR3pSMVBIRjlZMW4vTjI5MXZY
            b1BBeUxhUzVSZENGUlZweC9Yek1OdTQKLS0tIEh0NkdPVlJXeklnT2ZhaGZadEJH
            cEwyV3ZISWUwdkZOMGFuazlHYzJPajgK5viyq12gCEV6/6fEZHNHpld9wHK4OW58
            1Jaw10gNxlkV5jNg/+FgJQHAoP3EQiwWvyDLxs2FO8vmiWAZklhOpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-24T17:11:38Z"
    mac: ENC[AES256_GCM,data:K8KpHgG5kDlJ233R6EwZb9z0xym23m0RzwVKw3W1fdJbUQ1p3UnAP6h+ptvqNzr+/NH3HA861uo1PhRvgvaeIcW5B7KJc2/o+xfK9T+A8iSZXsk0hvH2cWC+38y8G7RNDy3i2ScbU7SYGODar2Pp4eYmWG2PNTPU64Zhdr5sZCc=,iv:wSGXl8P8KZZrU6XVJ2jG+PnEClW3JhBr9T9jYExk0E0=,tag:5bR5hcZpp4zNK0PC06AjBg==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml)$
    version: 3.7.1
