[SERVICE]
    Flush        1
    Log_Level    info
    Parsers_File parsers.conf

    storage.type filesystem
    storage.path /buffers
    storage.sync normal
    storage.backlog.mem_limit 50M

# access (stdout)
[FILTER]
    Name          rewrite_tag
    Match         nginx.raw
    Rule          $stream ^stdout$ nginx.access false

# error (stderr)
[FILTER]
    Name          rewrite_tag
    Match         nginx.raw
    Rule          $stream ^stderr$ nginx.error false

[FILTER]
    Name          parser
    Match         nginx.access
    Key_Name      log
    Parser        nginx_access
    Reserve_Data  On

[FILTER]
    Name          parser
    Match         nginx.error
    Key_Name      log
    Parser        nginx_error
    Reserve_Data  On

[FILTER]
    Name    modify
    Match   nginx.access
    Add     endpoint $request

[FILTER]
    Name    modify
    Match   nginx.access
    Convert status integer
    Convert body_bytes_sent integer
    Convert request_time float

[FILTER]
    Name          modify
    Match         nginx.*
    Add           service ingress-nginx

@INCLUDE input-kubernetes.conf
@INCLUDE output.conf