[INPUT]
    Name              tail
    Path              /var/log/containers/*ingress-nginx-controller*.log
    Parser            cri
    Tag               nginx.raw
    Mem_Buf_Limit     150MB
    Skip_Long_Lines   On
    Refresh_Interval  5

    storage.type      filesystem