[PARSER]
    Name        json
    Format      json
    Time_Key    time
    Time_Format %d/%b/%Y:%H:%M:%S %z

[PARSER]
    Name        cri
    Format      regex
    Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<flags>[^ ]*) (?<log>.*)$
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S.%L%z

# ACCESS LOG
[PARSER]
    Name   nginx_access
    Format regex
    Regex  ^(?<remote_addr>[^ ]*) - (?<remote_user>[^ ]*) \[(?<time_local>[^\]]*)\] "(?<method>\S+) (?<request>[^"]*) (?<protocol>[^"]*)" (?<status>\d+) (?<body_bytes_sent>\d+) "(?<referer>[^"]*)" "(?<agent>[^"]*)" "(?<x_forwarded_for>[^"]*)" "(?<upstream>[^"]*)" "(?<request_time>[^"]*)"
    Time_Key time_local
    Time_Format %d/%b/%Y:%H:%M:%S %z

# ERROR LOG
[PARSER]
    Name   nginx_error
    Format regex
    Regex  ^(?<time>\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}) \[(?<level>[^\]]+)\] (?<pid>\d+)#(?<tid>\d+): \*(?<connection>\d+) (?<message>.*)$
    Time_Key time
    Time_Format %Y/%m/%d %H:%M:%S