apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: selfsigned-issuer
spec:
    selfSigned: {}
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWHFwblNIcCtpMTdndTVw
            RU1zU3ZubHhXN3p0SnVyWHVJUVk2OENjTTMwCmVLV25CVmgxbUFWREtqRFJZTENk
            TnNRMlM5WVl1MDZqdmF6bXdteitFWTQKLS0tIEtmeHlZSDNnQ05YbS9jNURwczRO
            NTd5MzQrWXFUSUJJWVcrdlFLUlRVUnMKXUYf32SE1AfM8AS10e6otPewXOiV9B6l
            jrcqBiCtj66e3Tckd2lq+bRJNrnlpW9oEYWU1cAhYFhj92cNk8X+nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-15T18:57:17Z"
    mac: ENC[AES256_GCM,data:rs8/IVAlhK0i1fcftoNcFPb7J+ZOglF0G6BsCw/StJ/bC3VtAJUmu1OjP2WsPUOPYOAbLs3RGX2ZaMsQ3ScBVFbxNWwbhKe/ZQ+m3wgpkXdxTwa4HeXCWTij6rGGIFkVGjiG23QN34GdXP8kfILJK2FQfPpgdsv2W7uzy474f2g=,iv:ZZWOQqOyRtfQ+iCMuCfY1syh/cwagGGiPQBtQwmmnAE=,tag:hChaDmPhPBKgxuiXNeBrjg==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token)$
    version: 3.7.1
---
apiVersion: v1
kind: Namespace
metadata:
    name: cert-comintern
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWHFwblNIcCtpMTdndTVw
            RU1zU3ZubHhXN3p0SnVyWHVJUVk2OENjTTMwCmVLV25CVmgxbUFWREtqRFJZTENk
            TnNRMlM5WVl1MDZqdmF6bXdteitFWTQKLS0tIEtmeHlZSDNnQ05YbS9jNURwczRO
            NTd5MzQrWXFUSUJJWVcrdlFLUlRVUnMKXUYf32SE1AfM8AS10e6otPewXOiV9B6l
            jrcqBiCtj66e3Tckd2lq+bRJNrnlpW9oEYWU1cAhYFhj92cNk8X+nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-15T18:57:17Z"
    mac: ENC[AES256_GCM,data:rs8/IVAlhK0i1fcftoNcFPb7J+ZOglF0G6BsCw/StJ/bC3VtAJUmu1OjP2WsPUOPYOAbLs3RGX2ZaMsQ3ScBVFbxNWwbhKe/ZQ+m3wgpkXdxTwa4HeXCWTij6rGGIFkVGjiG23QN34GdXP8kfILJK2FQfPpgdsv2W7uzy474f2g=,iv:ZZWOQqOyRtfQ+iCMuCfY1syh/cwagGGiPQBtQwmmnAE=,tag:hChaDmPhPBKgxuiXNeBrjg==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token)$
    version: 3.7.1
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: comintern-cert
    namespace: cert-comintern
spec:
    secretName: comintern-cert-tls
    # 1 year
    duration: 8760h
    # 15 days
    renewBefore: 360h
    subject:
        organizations:
            - Comintern
    commonName: comintern.local
    dnsNames:
        - comintern.local
        - '*.comintern.local'
    issuerRef:
        name: selfsigned-issuer
        kind: ClusterIssuer
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWHFwblNIcCtpMTdndTVw
            RU1zU3ZubHhXN3p0SnVyWHVJUVk2OENjTTMwCmVLV25CVmgxbUFWREtqRFJZTENk
            TnNRMlM5WVl1MDZqdmF6bXdteitFWTQKLS0tIEtmeHlZSDNnQ05YbS9jNURwczRO
            NTd5MzQrWXFUSUJJWVcrdlFLUlRVUnMKXUYf32SE1AfM8AS10e6otPewXOiV9B6l
            jrcqBiCtj66e3Tckd2lq+bRJNrnlpW9oEYWU1cAhYFhj92cNk8X+nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-15T18:57:17Z"
    mac: ENC[AES256_GCM,data:rs8/IVAlhK0i1fcftoNcFPb7J+ZOglF0G6BsCw/StJ/bC3VtAJUmu1OjP2WsPUOPYOAbLs3RGX2ZaMsQ3ScBVFbxNWwbhKe/ZQ+m3wgpkXdxTwa4HeXCWTij6rGGIFkVGjiG23QN34GdXP8kfILJK2FQfPpgdsv2W7uzy474f2g=,iv:ZZWOQqOyRtfQ+iCMuCfY1syh/cwagGGiPQBtQwmmnAE=,tag:hChaDmPhPBKgxuiXNeBrjg==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token)$
    version: 3.7.1
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: cert-nfs-pv
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
        server: nas.comintern.local
        path: /mnt/trash_pool/misc/certs
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWHFwblNIcCtpMTdndTVw
            RU1zU3ZubHhXN3p0SnVyWHVJUVk2OENjTTMwCmVLV25CVmgxbUFWREtqRFJZTENk
            TnNRMlM5WVl1MDZqdmF6bXdteitFWTQKLS0tIEtmeHlZSDNnQ05YbS9jNURwczRO
            NTd5MzQrWXFUSUJJWVcrdlFLUlRVUnMKXUYf32SE1AfM8AS10e6otPewXOiV9B6l
            jrcqBiCtj66e3Tckd2lq+bRJNrnlpW9oEYWU1cAhYFhj92cNk8X+nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-15T18:57:17Z"
    mac: ENC[AES256_GCM,data:rs8/IVAlhK0i1fcftoNcFPb7J+ZOglF0G6BsCw/StJ/bC3VtAJUmu1OjP2WsPUOPYOAbLs3RGX2ZaMsQ3ScBVFbxNWwbhKe/ZQ+m3wgpkXdxTwa4HeXCWTij6rGGIFkVGjiG23QN34GdXP8kfILJK2FQfPpgdsv2W7uzy474f2g=,iv:ZZWOQqOyRtfQ+iCMuCfY1syh/cwagGGiPQBtQwmmnAE=,tag:hChaDmPhPBKgxuiXNeBrjg==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token)$
    version: 3.7.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: cert-nfs-pvc
    namespace: cert-comintern
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 1Gi
    volumeName: cert-nfs-pv
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWHFwblNIcCtpMTdndTVw
            RU1zU3ZubHhXN3p0SnVyWHVJUVk2OENjTTMwCmVLV25CVmgxbUFWREtqRFJZTENk
            TnNRMlM5WVl1MDZqdmF6bXdteitFWTQKLS0tIEtmeHlZSDNnQ05YbS9jNURwczRO
            NTd5MzQrWXFUSUJJWVcrdlFLUlRVUnMKXUYf32SE1AfM8AS10e6otPewXOiV9B6l
            jrcqBiCtj66e3Tckd2lq+bRJNrnlpW9oEYWU1cAhYFhj92cNk8X+nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-15T18:57:17Z"
    mac: ENC[AES256_GCM,data:rs8/IVAlhK0i1fcftoNcFPb7J+ZOglF0G6BsCw/StJ/bC3VtAJUmu1OjP2WsPUOPYOAbLs3RGX2ZaMsQ3ScBVFbxNWwbhKe/ZQ+m3wgpkXdxTwa4HeXCWTij6rGGIFkVGjiG23QN34GdXP8kfILJK2FQfPpgdsv2W7uzy474f2g=,iv:ZZWOQqOyRtfQ+iCMuCfY1syh/cwagGGiPQBtQwmmnAE=,tag:hChaDmPhPBKgxuiXNeBrjg==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token)$
    version: 3.7.1
---
apiVersion: batch/v1
kind: CronJob
metadata:
    name: sync-cert-to-nfs
    namespace: cert-comintern
spec:
    # each 30 min
    schedule: '*/30 * * * *'
    jobTemplate:
        spec:
            template:
                spec:
                    restartPolicy: OnFailure
                    volumes:
                        - name: cert-secret
                          secret:
                            secretName: comintern-cert-tls
                        - name: cert-nfs
                          persistentVolumeClaim:
                            claimName: cert-nfs-pvc
                    containers:
                        - name: sync
                          image: busybox
                          command:
                            - /bin/sh
                            - -c
                          args:
                            - mkdir -p /nfs/comintern.local/ && cp /cert/tls.crt /nfs/comintern.local/comintern.crt && cp /cert/tls.key /nfs/comintern.local/comintern.key
                          volumeMounts:
                            - mountPath: /cert
                              name: cert-secret
                              readOnly: true
                            - mountPath: /nfs
                              name: cert-nfs
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWHFwblNIcCtpMTdndTVw
            RU1zU3ZubHhXN3p0SnVyWHVJUVk2OENjTTMwCmVLV25CVmgxbUFWREtqRFJZTENk
            TnNRMlM5WVl1MDZqdmF6bXdteitFWTQKLS0tIEtmeHlZSDNnQ05YbS9jNURwczRO
            NTd5MzQrWXFUSUJJWVcrdlFLUlRVUnMKXUYf32SE1AfM8AS10e6otPewXOiV9B6l
            jrcqBiCtj66e3Tckd2lq+bRJNrnlpW9oEYWU1cAhYFhj92cNk8X+nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-15T18:57:17Z"
    mac: ENC[AES256_GCM,data:rs8/IVAlhK0i1fcftoNcFPb7J+ZOglF0G6BsCw/StJ/bC3VtAJUmu1OjP2WsPUOPYOAbLs3RGX2ZaMsQ3ScBVFbxNWwbhKe/ZQ+m3wgpkXdxTwa4HeXCWTij6rGGIFkVGjiG23QN34GdXP8kfILJK2FQfPpgdsv2W7uzy474f2g=,iv:ZZWOQqOyRtfQ+iCMuCfY1syh/cwagGGiPQBtQwmmnAE=,tag:hChaDmPhPBKgxuiXNeBrjg==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: digitalocean-dns
    namespace: cert-manager
type: Opaque
stringData:
    access-token: ENC[AES256_GCM,data:QNA3z4YUFpmG8WYeBXD65mUpC/u07tvXgeDk7AIa9u31vfy6s6gIJeVZDpxjFQqYB/Ya6OwkvwnzMOeO93tfkYVmQ2Lmh7E=,iv:tPFKqgkCrvqp4+/7kaZvf7e2boxXTGh202WBi0QextM=,tag:XtTTd80+/vcw/EEIm5O4YQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWHFwblNIcCtpMTdndTVw
            RU1zU3ZubHhXN3p0SnVyWHVJUVk2OENjTTMwCmVLV25CVmgxbUFWREtqRFJZTENk
            TnNRMlM5WVl1MDZqdmF6bXdteitFWTQKLS0tIEtmeHlZSDNnQ05YbS9jNURwczRO
            NTd5MzQrWXFUSUJJWVcrdlFLUlRVUnMKXUYf32SE1AfM8AS10e6otPewXOiV9B6l
            jrcqBiCtj66e3Tckd2lq+bRJNrnlpW9oEYWU1cAhYFhj92cNk8X+nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-15T18:57:17Z"
    mac: ENC[AES256_GCM,data:rs8/IVAlhK0i1fcftoNcFPb7J+ZOglF0G6BsCw/StJ/bC3VtAJUmu1OjP2WsPUOPYOAbLs3RGX2ZaMsQ3ScBVFbxNWwbhKe/ZQ+m3wgpkXdxTwa4HeXCWTij6rGGIFkVGjiG23QN34GdXP8kfILJK2FQfPpgdsv2W7uzy474f2g=,iv:ZZWOQqOyRtfQ+iCMuCfY1syh/cwagGGiPQBtQwmmnAE=,tag:hChaDmPhPBKgxuiXNeBrjg==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token)$
    version: 3.7.1
---
apiVersion: v1
kind: Namespace
metadata:
    name: cert-srvx-cc
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWHFwblNIcCtpMTdndTVw
            RU1zU3ZubHhXN3p0SnVyWHVJUVk2OENjTTMwCmVLV25CVmgxbUFWREtqRFJZTENk
            TnNRMlM5WVl1MDZqdmF6bXdteitFWTQKLS0tIEtmeHlZSDNnQ05YbS9jNURwczRO
            NTd5MzQrWXFUSUJJWVcrdlFLUlRVUnMKXUYf32SE1AfM8AS10e6otPewXOiV9B6l
            jrcqBiCtj66e3Tckd2lq+bRJNrnlpW9oEYWU1cAhYFhj92cNk8X+nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-15T18:57:17Z"
    mac: ENC[AES256_GCM,data:rs8/IVAlhK0i1fcftoNcFPb7J+ZOglF0G6BsCw/StJ/bC3VtAJUmu1OjP2WsPUOPYOAbLs3RGX2ZaMsQ3ScBVFbxNWwbhKe/ZQ+m3wgpkXdxTwa4HeXCWTij6rGGIFkVGjiG23QN34GdXP8kfILJK2FQfPpgdsv2W7uzy474f2g=,iv:ZZWOQqOyRtfQ+iCMuCfY1syh/cwagGGiPQBtQwmmnAE=,tag:hChaDmPhPBKgxuiXNeBrjg==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token)$
    version: 3.7.1
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-dns
spec:
    acme:
        email: ENC[AES256_GCM,data:kEJphKBLUOZ3bSaTD3K63vw=,iv:JTo/okVTdpVQt19HioYnw7tZbLNh3DAbB00WZhPwKX4=,tag:hRDzcZjdqdVMeutx0a72sA==,type:str]
        server: https://acme-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
            name: ENC[AES256_GCM,data:LUgQeHPnWFm7Z5BQygHnP0XtEA==,iv:6w73m5OOFFTPERx/J6UaEpnRAtHRAyoLm/Ith9bocr4=,tag:WuVs5UGuwC9zzwsp/4a5Ug==,type:str]
        solvers:
            - dns01:
                digitalocean:
                    tokenSecretRef:
                        name: ENC[AES256_GCM,data:S9XHvd1RmcyTd18IW0dUOw==,iv:bC+yb8RETXSwalrFshmsVGWDPEAMYCn4RJcSXbCmdb4=,tag:SHn1NBGJVIsTr+aoBSTykQ==,type:str]
                        key: ENC[AES256_GCM,data:fgo9YRffe9PXP/iN,iv:qEOHrlOYG015qG0UZIDAuLih2TKmumAl81Lu2HfxcYQ=,tag:2NWaMmOJeZftrC+L1MbQCA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWHFwblNIcCtpMTdndTVw
            RU1zU3ZubHhXN3p0SnVyWHVJUVk2OENjTTMwCmVLV25CVmgxbUFWREtqRFJZTENk
            TnNRMlM5WVl1MDZqdmF6bXdteitFWTQKLS0tIEtmeHlZSDNnQ05YbS9jNURwczRO
            NTd5MzQrWXFUSUJJWVcrdlFLUlRVUnMKXUYf32SE1AfM8AS10e6otPewXOiV9B6l
            jrcqBiCtj66e3Tckd2lq+bRJNrnlpW9oEYWU1cAhYFhj92cNk8X+nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-15T18:57:17Z"
    mac: ENC[AES256_GCM,data:rs8/IVAlhK0i1fcftoNcFPb7J+ZOglF0G6BsCw/StJ/bC3VtAJUmu1OjP2WsPUOPYOAbLs3RGX2ZaMsQ3ScBVFbxNWwbhKe/ZQ+m3wgpkXdxTwa4HeXCWTij6rGGIFkVGjiG23QN34GdXP8kfILJK2FQfPpgdsv2W7uzy474f2g=,iv:ZZWOQqOyRtfQ+iCMuCfY1syh/cwagGGiPQBtQwmmnAE=,tag:hChaDmPhPBKgxuiXNeBrjg==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token)$
    version: 3.7.1
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: srvx-cc-wildcard
    namespace: cert-srvx-cc
spec:
    secretName: srvx-cc-tls
    issuerRef:
        name: letsencrypt-dns
        kind: ClusterIssuer
    commonName: '*.srvx.cc'
    dnsNames:
        - '*.srvx.cc'
        - srvx.cc
    privateKey:
        algorithm: RSA
        size: 2048
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWHFwblNIcCtpMTdndTVw
            RU1zU3ZubHhXN3p0SnVyWHVJUVk2OENjTTMwCmVLV25CVmgxbUFWREtqRFJZTENk
            TnNRMlM5WVl1MDZqdmF6bXdteitFWTQKLS0tIEtmeHlZSDNnQ05YbS9jNURwczRO
            NTd5MzQrWXFUSUJJWVcrdlFLUlRVUnMKXUYf32SE1AfM8AS10e6otPewXOiV9B6l
            jrcqBiCtj66e3Tckd2lq+bRJNrnlpW9oEYWU1cAhYFhj92cNk8X+nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-15T18:57:17Z"
    mac: ENC[AES256_GCM,data:rs8/IVAlhK0i1fcftoNcFPb7J+ZOglF0G6BsCw/StJ/bC3VtAJUmu1OjP2WsPUOPYOAbLs3RGX2ZaMsQ3ScBVFbxNWwbhKe/ZQ+m3wgpkXdxTwa4HeXCWTij6rGGIFkVGjiG23QN34GdXP8kfILJK2FQfPpgdsv2W7uzy474f2g=,iv:ZZWOQqOyRtfQ+iCMuCfY1syh/cwagGGiPQBtQwmmnAE=,tag:hChaDmPhPBKgxuiXNeBrjg==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token)$
    version: 3.7.1
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
    name: cert-manager-rules
    namespace: cert-manager
spec:
    groups:
        - name: cert-manager.rules
          rules:
            - alert: CertificateExpiringSoon
              expr: (certmanager_certificate_expiration_timestamp_seconds - time()) < 86400 * 7
              for: 10m
              labels:
                severity: warning
              annotations:
                summary: Certificate {{ $labels.name }} is expiring soon
                description: Certificate {{ $labels.name }} in namespace {{ $labels.namespace }} will expire in less than 7 days.
            - alert: CertificateExpired
              expr: (certmanager_certificate_expiration_timestamp_seconds - time()) < 0
              for: 10m
              labels:
                severity: critical
              annotations:
                summary: Certificate {{ $labels.name }} has expired
                description: Certificate {{ $labels.name }} in namespace {{ $labels.namespace }} has expired.
            - alert: CertificateNotReady
              expr: certmanager_certificate_ready_status{condition="Ready",status="false"} == 1
              for: 10m
              labels:
                severity: critical
              annotations:
                summary: Certificate {{ $labels.name }} is not ready
                description: Certificate {{ $labels.name }} in namespace {{ $labels.namespace }} is not ready.
            - alert: IssuerNotReady
              expr: certmanager_issuer_ready_status{condition="Ready",status="false"} == 1
              for: 10m
              labels:
                severity: critical
              annotations:
                summary: Issuer {{ $labels.name }} is not ready
                description: Issuer {{ $labels.name }} in namespace {{ $labels.namespace }} is not ready.
            - alert: ClusterIssuerNotReady
              expr: certmanager_clusterissuer_ready_status{condition="Ready",status="false"} == 1
              for: 10m
              labels:
                severity: critical
              annotations:
                summary: ClusterIssuer {{ $labels.name }} is not ready
                description: ClusterIssuer {{ $labels.name }} is not ready.
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWHFwblNIcCtpMTdndTVw
            RU1zU3ZubHhXN3p0SnVyWHVJUVk2OENjTTMwCmVLV25CVmgxbUFWREtqRFJZTENk
            TnNRMlM5WVl1MDZqdmF6bXdteitFWTQKLS0tIEtmeHlZSDNnQ05YbS9jNURwczRO
            NTd5MzQrWXFUSUJJWVcrdlFLUlRVUnMKXUYf32SE1AfM8AS10e6otPewXOiV9B6l
            jrcqBiCtj66e3Tckd2lq+bRJNrnlpW9oEYWU1cAhYFhj92cNk8X+nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-15T18:57:17Z"
    mac: ENC[AES256_GCM,data:rs8/IVAlhK0i1fcftoNcFPb7J+ZOglF0G6BsCw/StJ/bC3VtAJUmu1OjP2WsPUOPYOAbLs3RGX2ZaMsQ3ScBVFbxNWwbhKe/ZQ+m3wgpkXdxTwa4HeXCWTij6rGGIFkVGjiG23QN34GdXP8kfILJK2FQfPpgdsv2W7uzy474f2g=,iv:ZZWOQqOyRtfQ+iCMuCfY1syh/cwagGGiPQBtQwmmnAE=,tag:hChaDmPhPBKgxuiXNeBrjg==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token)$
    version: 3.7.1
