apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: selfsigned-issuer
spec:
    selfSigned: {}
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzKzM5UUhoZFNnRDQ3Q25Y
            dWlURFpySXNWdzd6NmJoa0htYmxhR1VsaXhnCm1oTUNWYVVBNXVxWDVJZXJuOXFn
            Z0llQTVsRE94RHhZRjRKVUZqWGxWbTgKLS0tIGVzVXA1azJxS2MzbG9ZdUJ6QTlE
            WloxdlU5RVlQUThGbGRmSmU0Y25uQ2MKi4nDODhOKcNli5lMEv+r5zBKxbwTr8QX
            ETW94M4HVisTvWvNrLfhwOSZAeVjfhxHEifzuA6zDD9noOWEvctkyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-22T18:32:04Z"
    mac: ENC[AES256_GCM,data:bVOfkrqZsEjHOX5q5KkQ6VD/+QN+Ys+zEPtPB9Q0cX8JTKHHzM5lMEWVPF5f2WmmkEMiS6g3nRHb3vvDW9pQsX4YaLrbGziJZu2NhX69PTTo/VsvU7ddDjQPSzdLY0dzE3jt9S2+sZRDkqR5gBu6PkEptItJ4vRWBC+SrBXEcoM=,iv:a0fkPILIACXBP9XITmL0IuQJNQ6YMlO8janNDDeqfpo=,tag:s8r9HiQqvywbI7cnQypQJA==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token)$
    version: 3.7.1
---
apiVersion: v1
kind: Namespace
metadata:
    name: cert-comintern
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzKzM5UUhoZFNnRDQ3Q25Y
            dWlURFpySXNWdzd6NmJoa0htYmxhR1VsaXhnCm1oTUNWYVVBNXVxWDVJZXJuOXFn
            Z0llQTVsRE94RHhZRjRKVUZqWGxWbTgKLS0tIGVzVXA1azJxS2MzbG9ZdUJ6QTlE
            WloxdlU5RVlQUThGbGRmSmU0Y25uQ2MKi4nDODhOKcNli5lMEv+r5zBKxbwTr8QX
            ETW94M4HVisTvWvNrLfhwOSZAeVjfhxHEifzuA6zDD9noOWEvctkyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-22T18:32:04Z"
    mac: ENC[AES256_GCM,data:bVOfkrqZsEjHOX5q5KkQ6VD/+QN+Ys+zEPtPB9Q0cX8JTKHHzM5lMEWVPF5f2WmmkEMiS6g3nRHb3vvDW9pQsX4YaLrbGziJZu2NhX69PTTo/VsvU7ddDjQPSzdLY0dzE3jt9S2+sZRDkqR5gBu6PkEptItJ4vRWBC+SrBXEcoM=,iv:a0fkPILIACXBP9XITmL0IuQJNQ6YMlO8janNDDeqfpo=,tag:s8r9HiQqvywbI7cnQypQJA==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token)$
    version: 3.7.1
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: comintern-cert
    namespace: cert-comintern
spec:
    secretName: comintern-cert-tls
    # 1 year
    duration: 8760h
    # 15 days
    renewBefore: 360h
    subject:
        organizations:
            - Comintern
    commonName: comintern.local
    dnsNames:
        - comintern.local
        - '*.comintern.local'
    issuerRef:
        name: selfsigned-issuer
        kind: ClusterIssuer
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzKzM5UUhoZFNnRDQ3Q25Y
            dWlURFpySXNWdzd6NmJoa0htYmxhR1VsaXhnCm1oTUNWYVVBNXVxWDVJZXJuOXFn
            Z0llQTVsRE94RHhZRjRKVUZqWGxWbTgKLS0tIGVzVXA1azJxS2MzbG9ZdUJ6QTlE
            WloxdlU5RVlQUThGbGRmSmU0Y25uQ2MKi4nDODhOKcNli5lMEv+r5zBKxbwTr8QX
            ETW94M4HVisTvWvNrLfhwOSZAeVjfhxHEifzuA6zDD9noOWEvctkyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-22T18:32:04Z"
    mac: ENC[AES256_GCM,data:bVOfkrqZsEjHOX5q5KkQ6VD/+QN+Ys+zEPtPB9Q0cX8JTKHHzM5lMEWVPF5f2WmmkEMiS6g3nRHb3vvDW9pQsX4YaLrbGziJZu2NhX69PTTo/VsvU7ddDjQPSzdLY0dzE3jt9S2+sZRDkqR5gBu6PkEptItJ4vRWBC+SrBXEcoM=,iv:a0fkPILIACXBP9XITmL0IuQJNQ6YMlO8janNDDeqfpo=,tag:s8r9HiQqvywbI7cnQypQJA==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token)$
    version: 3.7.1
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: cert-nfs-pv
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
        server: nas.comintern.local
        path: /mnt/trash_pool/misc/certs
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzKzM5UUhoZFNnRDQ3Q25Y
            dWlURFpySXNWdzd6NmJoa0htYmxhR1VsaXhnCm1oTUNWYVVBNXVxWDVJZXJuOXFn
            Z0llQTVsRE94RHhZRjRKVUZqWGxWbTgKLS0tIGVzVXA1azJxS2MzbG9ZdUJ6QTlE
            WloxdlU5RVlQUThGbGRmSmU0Y25uQ2MKi4nDODhOKcNli5lMEv+r5zBKxbwTr8QX
            ETW94M4HVisTvWvNrLfhwOSZAeVjfhxHEifzuA6zDD9noOWEvctkyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-22T18:32:04Z"
    mac: ENC[AES256_GCM,data:bVOfkrqZsEjHOX5q5KkQ6VD/+QN+Ys+zEPtPB9Q0cX8JTKHHzM5lMEWVPF5f2WmmkEMiS6g3nRHb3vvDW9pQsX4YaLrbGziJZu2NhX69PTTo/VsvU7ddDjQPSzdLY0dzE3jt9S2+sZRDkqR5gBu6PkEptItJ4vRWBC+SrBXEcoM=,iv:a0fkPILIACXBP9XITmL0IuQJNQ6YMlO8janNDDeqfpo=,tag:s8r9HiQqvywbI7cnQypQJA==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token)$
    version: 3.7.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: cert-nfs-pvc
    namespace: cert-comintern
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 1Gi
    volumeName: cert-nfs-pv
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzKzM5UUhoZFNnRDQ3Q25Y
            dWlURFpySXNWdzd6NmJoa0htYmxhR1VsaXhnCm1oTUNWYVVBNXVxWDVJZXJuOXFn
            Z0llQTVsRE94RHhZRjRKVUZqWGxWbTgKLS0tIGVzVXA1azJxS2MzbG9ZdUJ6QTlE
            WloxdlU5RVlQUThGbGRmSmU0Y25uQ2MKi4nDODhOKcNli5lMEv+r5zBKxbwTr8QX
            ETW94M4HVisTvWvNrLfhwOSZAeVjfhxHEifzuA6zDD9noOWEvctkyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-22T18:32:04Z"
    mac: ENC[AES256_GCM,data:bVOfkrqZsEjHOX5q5KkQ6VD/+QN+Ys+zEPtPB9Q0cX8JTKHHzM5lMEWVPF5f2WmmkEMiS6g3nRHb3vvDW9pQsX4YaLrbGziJZu2NhX69PTTo/VsvU7ddDjQPSzdLY0dzE3jt9S2+sZRDkqR5gBu6PkEptItJ4vRWBC+SrBXEcoM=,iv:a0fkPILIACXBP9XITmL0IuQJNQ6YMlO8janNDDeqfpo=,tag:s8r9HiQqvywbI7cnQypQJA==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token)$
    version: 3.7.1
---
apiVersion: batch/v1
kind: CronJob
metadata:
    name: sync-cert-to-nfs
    namespace: cert-comintern
spec:
    # each 30 min
    schedule: '*/30 * * * *'
    jobTemplate:
        spec:
            template:
                spec:
                    restartPolicy: OnFailure
                    volumes:
                        - name: cert-secret
                          secret:
                            secretName: comintern-cert-tls
                        - name: cert-nfs
                          persistentVolumeClaim:
                            claimName: cert-nfs-pvc
                    containers:
                        - name: sync
                          image: busybox
                          command:
                            - /bin/sh
                            - -c
                          args:
                            - mkdir -p /nfs/comintern.local/ && cp /cert/tls.crt /nfs/comintern.local/comintern.crt && cp /cert/tls.key /nfs/comintern.local/comintern.key
                          volumeMounts:
                            - mountPath: /cert
                              name: cert-secret
                              readOnly: true
                            - mountPath: /nfs
                              name: cert-nfs
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzKzM5UUhoZFNnRDQ3Q25Y
            dWlURFpySXNWdzd6NmJoa0htYmxhR1VsaXhnCm1oTUNWYVVBNXVxWDVJZXJuOXFn
            Z0llQTVsRE94RHhZRjRKVUZqWGxWbTgKLS0tIGVzVXA1azJxS2MzbG9ZdUJ6QTlE
            WloxdlU5RVlQUThGbGRmSmU0Y25uQ2MKi4nDODhOKcNli5lMEv+r5zBKxbwTr8QX
            ETW94M4HVisTvWvNrLfhwOSZAeVjfhxHEifzuA6zDD9noOWEvctkyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-22T18:32:04Z"
    mac: ENC[AES256_GCM,data:bVOfkrqZsEjHOX5q5KkQ6VD/+QN+Ys+zEPtPB9Q0cX8JTKHHzM5lMEWVPF5f2WmmkEMiS6g3nRHb3vvDW9pQsX4YaLrbGziJZu2NhX69PTTo/VsvU7ddDjQPSzdLY0dzE3jt9S2+sZRDkqR5gBu6PkEptItJ4vRWBC+SrBXEcoM=,iv:a0fkPILIACXBP9XITmL0IuQJNQ6YMlO8janNDDeqfpo=,tag:s8r9HiQqvywbI7cnQypQJA==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: digitalocean-dns
    namespace: cert-manager
type: Opaque
stringData:
    access-token: ENC[AES256_GCM,data:zOQF1wtKfPB8omZz2dE+DZbJTXMNesaDbQfFzfYD2qGPRFmO7zO9lXYi0n7ic4SD+DJjXfmkJ5Qk/KNyoux66PsidX3oArk=,iv:OgotNY1nfqtQ5sI0ca3kD0XZzV/eGVxqeTf491X6NQo=,tag:dqIu2mKl8vaZECtMDKCwKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzKzM5UUhoZFNnRDQ3Q25Y
            dWlURFpySXNWdzd6NmJoa0htYmxhR1VsaXhnCm1oTUNWYVVBNXVxWDVJZXJuOXFn
            Z0llQTVsRE94RHhZRjRKVUZqWGxWbTgKLS0tIGVzVXA1azJxS2MzbG9ZdUJ6QTlE
            WloxdlU5RVlQUThGbGRmSmU0Y25uQ2MKi4nDODhOKcNli5lMEv+r5zBKxbwTr8QX
            ETW94M4HVisTvWvNrLfhwOSZAeVjfhxHEifzuA6zDD9noOWEvctkyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-22T18:32:04Z"
    mac: ENC[AES256_GCM,data:bVOfkrqZsEjHOX5q5KkQ6VD/+QN+Ys+zEPtPB9Q0cX8JTKHHzM5lMEWVPF5f2WmmkEMiS6g3nRHb3vvDW9pQsX4YaLrbGziJZu2NhX69PTTo/VsvU7ddDjQPSzdLY0dzE3jt9S2+sZRDkqR5gBu6PkEptItJ4vRWBC+SrBXEcoM=,iv:a0fkPILIACXBP9XITmL0IuQJNQ6YMlO8janNDDeqfpo=,tag:s8r9HiQqvywbI7cnQypQJA==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token)$
    version: 3.7.1
---
apiVersion: v1
kind: Namespace
metadata:
    name: gateway
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzKzM5UUhoZFNnRDQ3Q25Y
            dWlURFpySXNWdzd6NmJoa0htYmxhR1VsaXhnCm1oTUNWYVVBNXVxWDVJZXJuOXFn
            Z0llQTVsRE94RHhZRjRKVUZqWGxWbTgKLS0tIGVzVXA1azJxS2MzbG9ZdUJ6QTlE
            WloxdlU5RVlQUThGbGRmSmU0Y25uQ2MKi4nDODhOKcNli5lMEv+r5zBKxbwTr8QX
            ETW94M4HVisTvWvNrLfhwOSZAeVjfhxHEifzuA6zDD9noOWEvctkyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-22T18:32:04Z"
    mac: ENC[AES256_GCM,data:bVOfkrqZsEjHOX5q5KkQ6VD/+QN+Ys+zEPtPB9Q0cX8JTKHHzM5lMEWVPF5f2WmmkEMiS6g3nRHb3vvDW9pQsX4YaLrbGziJZu2NhX69PTTo/VsvU7ddDjQPSzdLY0dzE3jt9S2+sZRDkqR5gBu6PkEptItJ4vRWBC+SrBXEcoM=,iv:a0fkPILIACXBP9XITmL0IuQJNQ6YMlO8janNDDeqfpo=,tag:s8r9HiQqvywbI7cnQypQJA==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token)$
    version: 3.7.1
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-dns
spec:
    acme:
        email: ENC[AES256_GCM,data:cD9KZ0iPgIjo310JiImaaV8=,iv:I72WwvOMroPvAsMxFVoyKqXqRXP6PzcYwMqTjCJsqBM=,tag:Y2sFm+lm0zfBdHjRtzK6WA==,type:str]
        server: https://acme-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
            name: ENC[AES256_GCM,data:ERaPEIW9i4AjkvXH9Pl9gGtZ4A==,iv:yrcdjwSHDosKGN1hBVtkXUkjwks62A6j+InMqp+vBSQ=,tag:CPjaSfsNcYF/ht343pbtzw==,type:str]
        solvers:
            - dns01:
                digitalocean:
                    tokenSecretRef:
                        name: ENC[AES256_GCM,data:HB526ajQck+rGC09vDMeRQ==,iv:4s5sbgDDoD/g/BI4eXlXrce3XILtTg4MNViFQwF51bw=,tag:5IA3WW34f4XKNp65YZDSBQ==,type:str]
                        key: ENC[AES256_GCM,data:5C9ojLw3vr6lTcb0,iv:JPXcWyRZIoWydfX+x6FgD3w2D+dlrEc3y73TS3wS+a0=,tag:/wzhm0AgNzQcYL/eJp2cgg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzKzM5UUhoZFNnRDQ3Q25Y
            dWlURFpySXNWdzd6NmJoa0htYmxhR1VsaXhnCm1oTUNWYVVBNXVxWDVJZXJuOXFn
            Z0llQTVsRE94RHhZRjRKVUZqWGxWbTgKLS0tIGVzVXA1azJxS2MzbG9ZdUJ6QTlE
            WloxdlU5RVlQUThGbGRmSmU0Y25uQ2MKi4nDODhOKcNli5lMEv+r5zBKxbwTr8QX
            ETW94M4HVisTvWvNrLfhwOSZAeVjfhxHEifzuA6zDD9noOWEvctkyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-22T18:32:04Z"
    mac: ENC[AES256_GCM,data:bVOfkrqZsEjHOX5q5KkQ6VD/+QN+Ys+zEPtPB9Q0cX8JTKHHzM5lMEWVPF5f2WmmkEMiS6g3nRHb3vvDW9pQsX4YaLrbGziJZu2NhX69PTTo/VsvU7ddDjQPSzdLY0dzE3jt9S2+sZRDkqR5gBu6PkEptItJ4vRWBC+SrBXEcoM=,iv:a0fkPILIACXBP9XITmL0IuQJNQ6YMlO8janNDDeqfpo=,tag:s8r9HiQqvywbI7cnQypQJA==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token)$
    version: 3.7.1
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: srvx-cc-wildcard
    namespace: gateway
spec:
    secretName: srvx-cc-tls
    issuerRef:
        name: letsencrypt-dns
        kind: ClusterIssuer
    commonName: '*.srvx.cc'
    dnsNames:
        - '*.srvx.cc'
        - srvx.cc
    privateKey:
        algorithm: RSA
        size: 2048
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzKzM5UUhoZFNnRDQ3Q25Y
            dWlURFpySXNWdzd6NmJoa0htYmxhR1VsaXhnCm1oTUNWYVVBNXVxWDVJZXJuOXFn
            Z0llQTVsRE94RHhZRjRKVUZqWGxWbTgKLS0tIGVzVXA1azJxS2MzbG9ZdUJ6QTlE
            WloxdlU5RVlQUThGbGRmSmU0Y25uQ2MKi4nDODhOKcNli5lMEv+r5zBKxbwTr8QX
            ETW94M4HVisTvWvNrLfhwOSZAeVjfhxHEifzuA6zDD9noOWEvctkyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-22T18:32:04Z"
    mac: ENC[AES256_GCM,data:bVOfkrqZsEjHOX5q5KkQ6VD/+QN+Ys+zEPtPB9Q0cX8JTKHHzM5lMEWVPF5f2WmmkEMiS6g3nRHb3vvDW9pQsX4YaLrbGziJZu2NhX69PTTo/VsvU7ddDjQPSzdLY0dzE3jt9S2+sZRDkqR5gBu6PkEptItJ4vRWBC+SrBXEcoM=,iv:a0fkPILIACXBP9XITmL0IuQJNQ6YMlO8janNDDeqfpo=,tag:s8r9HiQqvywbI7cnQypQJA==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token)$
    version: 3.7.1
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
    name: cert-manager-rules
    namespace: cert-manager
    labels:
        release: prometheus
spec:
    groups:
        - name: cert-manager.rules
          rules:
            - alert: CertificateExpiringSoon
              expr: (certmanager_certificate_expiration_timestamp_seconds - time()) < 86400 * 7
              for: 10m
              labels:
                severity: warning
              annotations:
                summary: Certificate {{ $labels.name }} is expiring soon
                description: Certificate {{ $labels.name }} in namespace {{ $labels.namespace }} will expire in less than 7 days.
            - alert: CertificateExpired
              expr: (certmanager_certificate_expiration_timestamp_seconds - time()) < 0
              for: 10m
              labels:
                severity: critical
              annotations:
                summary: Certificate {{ $labels.name }} has expired
                description: Certificate {{ $labels.name }} in namespace {{ $labels.namespace }} has expired.
            - alert: CertificateNotReady
              expr: certmanager_certificate_ready_status{condition="Ready",status="false"} == 1
              for: 10m
              labels:
                severity: critical
              annotations:
                summary: Certificate {{ $labels.name }} is not ready
                description: Certificate {{ $labels.name }} in namespace {{ $labels.namespace }} is not ready.
            - alert: IssuerNotReady
              expr: certmanager_issuer_ready_status{condition="Ready",status="false"} == 1
              for: 10m
              labels:
                severity: critical
              annotations:
                summary: Issuer {{ $labels.name }} is not ready
                description: Issuer {{ $labels.name }} in namespace {{ $labels.namespace }} is not ready.
            - alert: ClusterIssuerNotReady
              expr: certmanager_clusterissuer_ready_status{condition="Ready",status="false"} == 1
              for: 10m
              labels:
                severity: critical
              annotations:
                summary: ClusterIssuer {{ $labels.name }} is not ready
                description: ClusterIssuer {{ $labels.name }} is not ready.
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzKzM5UUhoZFNnRDQ3Q25Y
            dWlURFpySXNWdzd6NmJoa0htYmxhR1VsaXhnCm1oTUNWYVVBNXVxWDVJZXJuOXFn
            Z0llQTVsRE94RHhZRjRKVUZqWGxWbTgKLS0tIGVzVXA1azJxS2MzbG9ZdUJ6QTlE
            WloxdlU5RVlQUThGbGRmSmU0Y25uQ2MKi4nDODhOKcNli5lMEv+r5zBKxbwTr8QX
            ETW94M4HVisTvWvNrLfhwOSZAeVjfhxHEifzuA6zDD9noOWEvctkyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-22T18:32:04Z"
    mac: ENC[AES256_GCM,data:bVOfkrqZsEjHOX5q5KkQ6VD/+QN+Ys+zEPtPB9Q0cX8JTKHHzM5lMEWVPF5f2WmmkEMiS6g3nRHb3vvDW9pQsX4YaLrbGziJZu2NhX69PTTo/VsvU7ddDjQPSzdLY0dzE3jt9S2+sZRDkqR5gBu6PkEptItJ4vRWBC+SrBXEcoM=,iv:a0fkPILIACXBP9XITmL0IuQJNQ6YMlO8janNDDeqfpo=,tag:s8r9HiQqvywbI7cnQypQJA==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token)$
    version: 3.7.1
