namespace: 'cert-manager'

extraArgs:
  - --enable-certificate-owner-ref=true
  - --cluster-resource-namespace=$(POD_NAMESPACE)
  - --controllers=*,certificaterequests-approver

crds:
  enabled: true
  keep: true

prometheus:
  enabled: true

webhook:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

cainjector:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

startupapicheck:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
