apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redis

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: redis-auth
    envs:
      - .env
    type: Opaque

resources:
  - namespace.yaml
  - redis-certificate.yaml
