apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-deployer
rules:
- apiGroups:
    - ""
    - apps
    - batch
    - networking.k8s.io
    - autoscaling
    - policy
    - storage.k8s.io
    - rbac.authorization.k8s.io
    - coordination.k8s.io
    - apiextensions.k8s.io
    - apiregistration.k8s.io
    - admissionregistration.k8s.io
    - metallb.io
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: jenkins-deployer
  apiGroup: rbac.authorization.k8s.io

