apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: local
    namespace: argocd
spec:
    description: Project for local k8s cluster
    sourceRepos:
        - https://github.com/nazmang/argocd-apps.git
        - https://kubernetes-sigs.github.io/external-dns/
        - https://aquasecurity.github.io/helm-charts/
        - https://github.com/raoulx24/trivy-operator-dashboard.git
        - https://helm.releases.hashicorp.com
        - https://*.github.io/*
        - https://*.github.com/*
        - https://stakater.github.io/stakater-charts
        - https://cloudhippie.github.io/charts
    destinations:
        - namespace: '*'
          server: https://kubernetes.default.svc
    clusterResourceWhitelist:
        - group: '*'
          kind: '*'
    namespaceResourceWhitelist:
        - group: '*'
          kind: '*'
    orphanedResources:
        warn: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQWMwYW5LQUVxTlNUdGdZ
            WFZmRi84THMvbEtBRE42UlBjOEdSZzdoQWd3CnV6d2ZRRjlBc3QyeXNOTE9hRTlk
            T1FUbzVmUDBXSUtrcFlBNlVDTTVWVzAKLS0tIGV6NXF1N3RpTjY4UStQUjJlamx5
            UWsxR0xiZkFMbVZmMUZ4NkVXNEphcGsKxc+1/atj0eE3RUqL3agSRDlkzCDnuUZ/
            OcEutst2jqD6ILeHcx1XI3bl+4xTOLbDF0B4YxFMtHZEr+VfLwlrvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T16:08:33Z"
    mac: ENC[AES256_GCM,data:mcOyqKfG+0sATidVvVbbqXi2Jrk4VpL9jolTDvoQ7ZNMlAMxof7UCgpw/0TYKNB8sfK0ESp76s7FVlPUcMyl+IKUFZCaZdeBSz78GEl+7RVMtQtUwe4HQXl/6XplR2Yx9a1ocao0IuZ33SY0q0m/LZeZMWgxrL3iUjPLP2hPN7I=,iv:skjUEQG0dC7hkRl/Vd2XuYdrz6Y+FSXzchASXTU3MRA=,tag:NWmtZ5+ZQaO2EOFuIWE+qA==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml|object-storage-configs.yaml|api-token|OPENSEARCH_.*)$
    version: 3.7.1
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: apps-root
    namespace: argocd
spec:
    project: local
    source:
        repoURL: https://github.com/nazmang/argocd-apps.git
        targetRevision: HEAD
        path: .
    destination:
        server: https://kubernetes.default.svc
        namespace: argocd
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQWMwYW5LQUVxTlNUdGdZ
            WFZmRi84THMvbEtBRE42UlBjOEdSZzdoQWd3CnV6d2ZRRjlBc3QyeXNOTE9hRTlk
            T1FUbzVmUDBXSUtrcFlBNlVDTTVWVzAKLS0tIGV6NXF1N3RpTjY4UStQUjJlamx5
            UWsxR0xiZkFMbVZmMUZ4NkVXNEphcGsKxc+1/atj0eE3RUqL3agSRDlkzCDnuUZ/
            OcEutst2jqD6ILeHcx1XI3bl+4xTOLbDF0B4YxFMtHZEr+VfLwlrvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T16:08:33Z"
    mac: ENC[AES256_GCM,data:mcOyqKfG+0sATidVvVbbqXi2Jrk4VpL9jolTDvoQ7ZNMlAMxof7UCgpw/0TYKNB8sfK0ESp76s7FVlPUcMyl+IKUFZCaZdeBSz78GEl+7RVMtQtUwe4HQXl/6XplR2Yx9a1ocao0IuZ33SY0q0m/LZeZMWgxrL3iUjPLP2hPN7I=,iv:skjUEQG0dC7hkRl/Vd2XuYdrz6Y+FSXzchASXTU3MRA=,tag:NWmtZ5+ZQaO2EOFuIWE+qA==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml|object-storage-configs.yaml|api-token|OPENSEARCH_.*)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: sops-age-key
    namespace: argocd
type: Opaque
stringData:
    SOPS_AGE_KEY: ENC[AES256_GCM,data:OmHfAXfD5DewjpJuuPMTsKUL1GiFiH20EuMaVogGtd/cWYWXeZg4uCEyTdqBREOaQq87pitTA2WxGCBRQwo7r0KqDf4JpuAa/uE=,iv:MxbIy3jD/cyuTd50knaRh7rR60m0bjOYZ9hmh/rMXqc=,tag:NlggVgR9HHSi1w2wYP/pzg==,type:str]
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#     name: argocd-vault-plugin
#     namespace: argocd
# data:
#     configManagementPlugins.yaml: |
#         apiVersion: argoproj.io/v1alpha1
#         kind: ConfigManagementPlugin
#         metadata:
#           name: argocd-vault-plugin
#           namespace: argocd
#         spec:
#           version: v1.0
#           init:
#             command: ["/bin/sh", "-c"]
#             args: ["echo 'Initializing argocd-vault-plugin'"]
#           generate:
#             command: ["/bin/sh", "-c"]
#             args: ["/usr/local/bin/sops -d $VALUES_FILE"]
#           discover:
#             find:
#               command: ["sh", "-c", "find . -maxdepth 1 -type f -name '*.enc.yaml' -print -quit"]
# ---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#     name: argocd-application-controller-hpa
#     namespace: argocd
# spec:
#     scaleTargetRef:
#         apiVersion: apps/v1
#         kind: Deployment
#         name: argocd-argo-cd-app-controller
#     minReplicas: 1
#     maxReplicas: 3
#     metrics:
#         - type: Resource
#           resource:
#             name: cpu
#             target:
#                 type: Utilization
#                 averageUtilization: 70
#         - type: Resource
#           resource:
#             name: memory
#             target:
#                 type: Utilization
#                 averageUtilization: 95
# ---
# apiVersion: autoscaling.k8s.io/v1
# kind: VerticalPodAutoscaler
# metadata:
#     name: argocd-argo-cd-repo-server-vpa
#     namespace: argocd
# spec:
#     targetRef:
#         apiVersion: apps/v1
#         kind: Deployment
#         name: argocd-argo-cd-repo-server
#     updatePolicy:
#         # Auto | Off | Initial
#         updateMode: Auto
#     resourcePolicy:
#         containerPolicies:
#             - containerName: '*'
#               minAllowed:
#                 cpu: 100m
#                 memory: 256Mi
#               maxAllowed:
#                 cpu: "1"
#                 memory: 756Mi
#               controlledResources:
#                 - cpu
#                 - memory
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQWMwYW5LQUVxTlNUdGdZ
            WFZmRi84THMvbEtBRE42UlBjOEdSZzdoQWd3CnV6d2ZRRjlBc3QyeXNOTE9hRTlk
            T1FUbzVmUDBXSUtrcFlBNlVDTTVWVzAKLS0tIGV6NXF1N3RpTjY4UStQUjJlamx5
            UWsxR0xiZkFMbVZmMUZ4NkVXNEphcGsKxc+1/atj0eE3RUqL3agSRDlkzCDnuUZ/
            OcEutst2jqD6ILeHcx1XI3bl+4xTOLbDF0B4YxFMtHZEr+VfLwlrvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T16:08:33Z"
    mac: ENC[AES256_GCM,data:mcOyqKfG+0sATidVvVbbqXi2Jrk4VpL9jolTDvoQ7ZNMlAMxof7UCgpw/0TYKNB8sfK0ESp76s7FVlPUcMyl+IKUFZCaZdeBSz78GEl+7RVMtQtUwe4HQXl/6XplR2Yx9a1ocao0IuZ33SY0q0m/LZeZMWgxrL3iUjPLP2hPN7I=,iv:skjUEQG0dC7hkRl/Vd2XuYdrz6Y+FSXzchASXTU3MRA=,tag:NWmtZ5+ZQaO2EOFuIWE+qA==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml|object-storage-configs.yaml|api-token|OPENSEARCH_.*)$
    version: 3.7.1
