apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: local
    namespace: argocd
spec:
    description: Project for local k8s cluster
    sourceRepos:
        - https://github.com/nazmang/argocd-apps.git
        - https://kubernetes-sigs.github.io/external-dns/
        - https://aquasecurity.github.io/helm-charts/
        - https://github.com/raoulx24/trivy-operator-dashboard.git
        - https://helm.releases.hashicorp.com
        - https://*.github.io/*
        - https://*.github.com/*
        - https://stakater.github.io/stakater-charts
        - https://cloudhippie.github.io/charts
    destinations:
        - namespace: '*'
          server: https://kubernetes.default.svc
    clusterResourceWhitelist:
        - group: '*'
          kind: '*'
    namespaceResourceWhitelist:
        - group: '*'
          kind: '*'
    orphanedResources:
        warn: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRWdrLzM4UjlCZXlkVFQw
            UW1EQmExTDR2ZWlPZ2E2d29FWFIrUTZNOTJrCjBhWmpJdi81MU82c0MwQlpBK1Mw
            S2hNWWd5RSsyL0NBTGVlcHljYzVhSTQKLS0tIEpYWjdJRmVwSFRVTGg0dDZ0TXZx
            RDRXa25WZU52NS8wWlFWU2VWUjJnSE0KbkeM8egbSIgTg3wkBxq9B49SHXkVAg0x
            QGZep2i+bExmvlajpgEWU3gtrUtNgrPB7CdY9cV37YJRenapy6ohCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T16:56:23Z"
    mac: ENC[AES256_GCM,data:nY+CgacbSXLGrOEFZMEhNU8xdWw2uG+7upU0NfmFppDyQzuGVj3RguersLBloqhVp0hXE3wG2pEjqqvQrgTRPT0iGZlatGZfd7XLRpBYNs/AaBA2iax9Col60w2n734gK9gaeyiY6i3NBv3tPx7kWx+fFN5FNug8RZhS0d9jbzk=,iv:VytfQExcK5OY7JKKiGyk96/1Ap3KbILbSpUomWaiA0A=,tag:XMwbpBSchIZ58cG1C16edQ==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml|object-storage-configs.yaml|api-token|OPENSEARCH_.*)$
    version: 3.7.1
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: apps-root
    namespace: argocd
spec:
    project: local
    source:
        repoURL: https://github.com/nazmang/argocd-apps.git
        targetRevision: HEAD
        path: .
    destination:
        server: https://kubernetes.default.svc
        namespace: argocd
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRWdrLzM4UjlCZXlkVFQw
            UW1EQmExTDR2ZWlPZ2E2d29FWFIrUTZNOTJrCjBhWmpJdi81MU82c0MwQlpBK1Mw
            S2hNWWd5RSsyL0NBTGVlcHljYzVhSTQKLS0tIEpYWjdJRmVwSFRVTGg0dDZ0TXZx
            RDRXa25WZU52NS8wWlFWU2VWUjJnSE0KbkeM8egbSIgTg3wkBxq9B49SHXkVAg0x
            QGZep2i+bExmvlajpgEWU3gtrUtNgrPB7CdY9cV37YJRenapy6ohCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T16:56:23Z"
    mac: ENC[AES256_GCM,data:nY+CgacbSXLGrOEFZMEhNU8xdWw2uG+7upU0NfmFppDyQzuGVj3RguersLBloqhVp0hXE3wG2pEjqqvQrgTRPT0iGZlatGZfd7XLRpBYNs/AaBA2iax9Col60w2n734gK9gaeyiY6i3NBv3tPx7kWx+fFN5FNug8RZhS0d9jbzk=,iv:VytfQExcK5OY7JKKiGyk96/1Ap3KbILbSpUomWaiA0A=,tag:XMwbpBSchIZ58cG1C16edQ==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml|object-storage-configs.yaml|api-token|OPENSEARCH_.*)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: sops-age-key
    namespace: argocd
type: Opaque
stringData:
    SOPS_AGE_KEY: ENC[AES256_GCM,data:npG6RqkUI1a+sbC99dWyUu2VPKaxyevHS4m3ReSnz9HxgRDHqSO3WgQj4h/9Zg0gBYNv5Aq6meCKRQgg1buPUfDjRYqUqS1ErGc=,iv:yWsGV0mW8828EDomUmKQSCP8a9eUZ0ucu8QL4sM3gqQ=,tag:50KpCIjFBcD913/y4G54tg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRWdrLzM4UjlCZXlkVFQw
            UW1EQmExTDR2ZWlPZ2E2d29FWFIrUTZNOTJrCjBhWmpJdi81MU82c0MwQlpBK1Mw
            S2hNWWd5RSsyL0NBTGVlcHljYzVhSTQKLS0tIEpYWjdJRmVwSFRVTGg0dDZ0TXZx
            RDRXa25WZU52NS8wWlFWU2VWUjJnSE0KbkeM8egbSIgTg3wkBxq9B49SHXkVAg0x
            QGZep2i+bExmvlajpgEWU3gtrUtNgrPB7CdY9cV37YJRenapy6ohCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T16:56:23Z"
    mac: ENC[AES256_GCM,data:nY+CgacbSXLGrOEFZMEhNU8xdWw2uG+7upU0NfmFppDyQzuGVj3RguersLBloqhVp0hXE3wG2pEjqqvQrgTRPT0iGZlatGZfd7XLRpBYNs/AaBA2iax9Col60w2n734gK9gaeyiY6i3NBv3tPx7kWx+fFN5FNug8RZhS0d9jbzk=,iv:VytfQExcK5OY7JKKiGyk96/1Ap3KbILbSpUomWaiA0A=,tag:XMwbpBSchIZ58cG1C16edQ==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml|object-storage-configs.yaml|api-token|OPENSEARCH_.*)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: redis-auth
    namespace: argocd
data:
    redis-password: ENC[AES256_GCM,data:Boqfizi8ddUiyBDxackYZvXRv49ykYyxfRFsX/9yyWLH7/HP,iv:LwjZ6ZEoSTQxia1Hx4qSw2uVtn8XYrFUL5Ws0x37Oh4=,tag:Z3aGbn557m9JEJCYbQoPDA==,type:str]
type: Opaque
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#     name: argocd-vault-plugin
#     namespace: argocd
# data:
#     configManagementPlugins.yaml: |
#         apiVersion: argoproj.io/v1alpha1
#         kind: ConfigManagementPlugin
#         metadata:
#           name: argocd-vault-plugin
#           namespace: argocd
#         spec:
#           version: v1.0
#           init:
#             command: ["/bin/sh", "-c"]
#             args: ["echo 'Initializing argocd-vault-plugin'"]
#           generate:
#             command: ["/bin/sh", "-c"]
#             args: ["/usr/local/bin/sops -d $VALUES_FILE"]
#           discover:
#             find:
#               command: ["sh", "-c", "find . -maxdepth 1 -type f -name '*.enc.yaml' -print -quit"]
# ---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#     name: argocd-application-controller-hpa
#     namespace: argocd
# spec:
#     scaleTargetRef:
#         apiVersion: apps/v1
#         kind: Deployment
#         name: argocd-argo-cd-app-controller
#     minReplicas: 1
#     maxReplicas: 3
#     metrics:
#         - type: Resource
#           resource:
#             name: cpu
#             target:
#                 type: Utilization
#                 averageUtilization: 70
#         - type: Resource
#           resource:
#             name: memory
#             target:
#                 type: Utilization
#                 averageUtilization: 95
# ---
# apiVersion: autoscaling.k8s.io/v1
# kind: VerticalPodAutoscaler
# metadata:
#     name: argocd-argo-cd-repo-server-vpa
#     namespace: argocd
# spec:
#     targetRef:
#         apiVersion: apps/v1
#         kind: Deployment
#         name: argocd-argo-cd-repo-server
#     updatePolicy:
#         # Auto | Off | Initial
#         updateMode: Auto
#     resourcePolicy:
#         containerPolicies:
#             - containerName: '*'
#               minAllowed:
#                 cpu: 100m
#                 memory: 256Mi
#               maxAllowed:
#                 cpu: "1"
#                 memory: 756Mi
#               controlledResources:
#                 - cpu
#                 - memory
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRWdrLzM4UjlCZXlkVFQw
            UW1EQmExTDR2ZWlPZ2E2d29FWFIrUTZNOTJrCjBhWmpJdi81MU82c0MwQlpBK1Mw
            S2hNWWd5RSsyL0NBTGVlcHljYzVhSTQKLS0tIEpYWjdJRmVwSFRVTGg0dDZ0TXZx
            RDRXa25WZU52NS8wWlFWU2VWUjJnSE0KbkeM8egbSIgTg3wkBxq9B49SHXkVAg0x
            QGZep2i+bExmvlajpgEWU3gtrUtNgrPB7CdY9cV37YJRenapy6ohCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T16:56:23Z"
    mac: ENC[AES256_GCM,data:nY+CgacbSXLGrOEFZMEhNU8xdWw2uG+7upU0NfmFppDyQzuGVj3RguersLBloqhVp0hXE3wG2pEjqqvQrgTRPT0iGZlatGZfd7XLRpBYNs/AaBA2iax9Col60w2n734gK9gaeyiY6i3NBv3tPx7kWx+fFN5FNug8RZhS0d9jbzk=,iv:VytfQExcK5OY7JKKiGyk96/1Ap3KbILbSpUomWaiA0A=,tag:XMwbpBSchIZ58cG1C16edQ==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml|object-storage-configs.yaml|api-token|OPENSEARCH_.*)$
    version: 3.7.1
