apiVersion: v1
kind: Secret
metadata:
    name: sops-age-key
    namespace: argocd
type: Opaque
stringData:
    SOPS_AGE_KEY: ENC[AES256_GCM,data:JJZsVnsKCW/+wn8gAcKPslh2EsIAmpfX4CMQBfNJYkIz0bAtnC6wX0NA+DXT1I/Zd0UIFMWPs8ip7yaiT5H3elYjZLjd6S/DUQg=,iv:mFkJR3L/YWSs5wbnWqPdXNsWMB9wbAXIU43Fr8KSeco=,tag:IS2XikzqP/CQPri9rR8nqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQm04ZGF3SGY3WFd1dkY1
            b0phalA5bFZGSmJDbGdQTmZNWEwrazNKamdBCnpTbWVRYjlSdlpPR25KUEtXL3dt
            cG5mZkxyUTlpd0pKU0lCUURmSWl1WUkKLS0tIHFESUJrZ2RtZkJKbmRoNWllUlBV
            cGtLcmgrVE5nbEswUjA4SStEVlZjWlEKs52ZYcI7UErq/0TEN+sLe6AjtFgrth1f
            0r/1HE/aGNztOK4VaVmGtfswZ+KB1g/mK6YClLK/2E4yZiGZPft7vQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T14:44:11Z"
    mac: ENC[AES256_GCM,data:2rsDMZVuYMK9C6zYL6BWiDToztN17G0Om+ZR6C+0iZAdJjZkfxRMlBNh1pMYN2G8ZIFa3IoW3isk2JNe/qAG3qKqHilC7d1T0OSORiGk4HXDXRRMoMEXU1MMEL5hzvFf9oQl7+fnMRO2anFYfyb0RDUMj8SiJITcINNeyR4RfaU=,iv:Q35dNRC38MwbmNHQaVAhceK71vQz7B8vl6yv8u7ve3M=,tag:3YsCryrl7FBpzYNKM9GSfw==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml|object-storage-configs.yaml|api-token|OPENSEARCH_.*)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: redis-auth
    namespace: argocd
data:
    redis-password: ENC[AES256_GCM,data:AjPsxXoWBav6pa4ood0YzopsPtz3GNJ7FgNBVDlU2uMUs5Pz,iv:5PxJzuOx53rpnBreVzkbjCcDNdwdyOj0mHH0jyoJB5k=,tag:EGCb2abpIdDbomSpcH7mJQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQm04ZGF3SGY3WFd1dkY1
            b0phalA5bFZGSmJDbGdQTmZNWEwrazNKamdBCnpTbWVRYjlSdlpPR25KUEtXL3dt
            cG5mZkxyUTlpd0pKU0lCUURmSWl1WUkKLS0tIHFESUJrZ2RtZkJKbmRoNWllUlBV
            cGtLcmgrVE5nbEswUjA4SStEVlZjWlEKs52ZYcI7UErq/0TEN+sLe6AjtFgrth1f
            0r/1HE/aGNztOK4VaVmGtfswZ+KB1g/mK6YClLK/2E4yZiGZPft7vQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T14:44:11Z"
    mac: ENC[AES256_GCM,data:2rsDMZVuYMK9C6zYL6BWiDToztN17G0Om+ZR6C+0iZAdJjZkfxRMlBNh1pMYN2G8ZIFa3IoW3isk2JNe/qAG3qKqHilC7d1T0OSORiGk4HXDXRRMoMEXU1MMEL5hzvFf9oQl7+fnMRO2anFYfyb0RDUMj8SiJITcINNeyR4RfaU=,iv:Q35dNRC38MwbmNHQaVAhceK71vQz7B8vl6yv8u7ve3M=,tag:3YsCryrl7FBpzYNKM9GSfw==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml|object-storage-configs.yaml|api-token|OPENSEARCH_.*)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: argocd-apps-repo
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
    type: git
    url: https://github.com/nazmang/argocd-apps.git
    username: nazmang
    password: ENC[AES256_GCM,data:yHgogrZQZLkmpYwCPmSjjslPr8t+CW/0ZrpM5sTuhmu5RQOL5RlvUmMAHADo+eR55i9/x7uJkWNPqYRz8/EyNzf7D/4W1adHze8BHOmC9zRAKEmfeoyQWYqQKYkY,iv:LT4J4kxVJ65O2xigxhJVbGMy/VsIUeiz+u1AczGy/ow=,tag:j+33Fm19CBTpC5EpHLPpTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQm04ZGF3SGY3WFd1dkY1
            b0phalA5bFZGSmJDbGdQTmZNWEwrazNKamdBCnpTbWVRYjlSdlpPR25KUEtXL3dt
            cG5mZkxyUTlpd0pKU0lCUURmSWl1WUkKLS0tIHFESUJrZ2RtZkJKbmRoNWllUlBV
            cGtLcmgrVE5nbEswUjA4SStEVlZjWlEKs52ZYcI7UErq/0TEN+sLe6AjtFgrth1f
            0r/1HE/aGNztOK4VaVmGtfswZ+KB1g/mK6YClLK/2E4yZiGZPft7vQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T14:44:11Z"
    mac: ENC[AES256_GCM,data:2rsDMZVuYMK9C6zYL6BWiDToztN17G0Om+ZR6C+0iZAdJjZkfxRMlBNh1pMYN2G8ZIFa3IoW3isk2JNe/qAG3qKqHilC7d1T0OSORiGk4HXDXRRMoMEXU1MMEL5hzvFf9oQl7+fnMRO2anFYfyb0RDUMj8SiJITcINNeyR4RfaU=,iv:Q35dNRC38MwbmNHQaVAhceK71vQz7B8vl6yv8u7ve3M=,tag:3YsCryrl7FBpzYNKM9GSfw==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml|object-storage-configs.yaml|api-token|OPENSEARCH_.*)$
    version: 3.7.1
