apiVersion: v1
kind: Secret
metadata:
    name: sops-age-key
    namespace: argocd
type: Opaque
stringData:
    SOPS_AGE_KEY: ENC[AES256_GCM,data:yUzjLcqAGSqoPTM1BhkKwivTJjahUY5rofprcoge9BDwLXJjNhy00HVeCne1NkUKoKhuYyuY/I3wYe17LtEbJrvALWDcN+gP3xU=,iv:ZAJN865/yRktbZNDyHT2m9IaJp6v3wU7G7TOWiFVLII=,tag:7SQqPkbKqWfev23ioTgB+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcytXSFhGeWxkdWx6SGVW
            L0dGZVJ0ZEdQMndFTnFxUUhNYWFLWjIxY2tZCmFVdWFJU0xqY1VOd3U2YjM2QlJo
            M3FXUzZYcHNyTGVraUZ5RmFyRzJ3WlEKLS0tIFRvVFJEcWlWU3VZRHdpQzZPVlhS
            M0JYOElCMUh1Tm9qY0NBTDFKWDNMQ00KxZhTMb1oeR7RbeLwpqmTh6l2/vy7OZtf
            8t5KSadSO42AT7RyucnQpdtoO0FCkSMlpJecpc/2xpmcEHMWUs24wA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T14:27:20Z"
    mac: ENC[AES256_GCM,data:o96O4+OS/muukyZ8kq+CEisJBwP7pQ6EB9b0K6oADT85ZkWweXHcB5gQIelrKnSicPMoEWrMmpf5k15n2TFXJls9InqTSdIuic1946Nyw0JoaTdp0zX19Ko/2XuH/8uvz8EgmcAb8b/B1+54yuR0kRtAylW7LJ/50noOyJxbraY=,iv:O05rWV8Y4UZ1U+SjCnoBuDa7ubR2h83kCKoNUz2dwYU=,tag:CpvS92KCE0tziN7Ya3/NkA==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml|object-storage-configs.yaml|api-token|OPENSEARCH_.*)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: redis-auth
    namespace: argocd
data:
    redis-password: ENC[AES256_GCM,data:qvPrnyaT51/jd3sXXPTxyG78UwHetlyx+84vhBmjzbRsgOiG,iv:13Uqa+WiLrN/MXQSd2TIPB1yOC95yVQngJTNTz58HF8=,tag:yxBD9rbS0be41vns0HtPVw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcytXSFhGeWxkdWx6SGVW
            L0dGZVJ0ZEdQMndFTnFxUUhNYWFLWjIxY2tZCmFVdWFJU0xqY1VOd3U2YjM2QlJo
            M3FXUzZYcHNyTGVraUZ5RmFyRzJ3WlEKLS0tIFRvVFJEcWlWU3VZRHdpQzZPVlhS
            M0JYOElCMUh1Tm9qY0NBTDFKWDNMQ00KxZhTMb1oeR7RbeLwpqmTh6l2/vy7OZtf
            8t5KSadSO42AT7RyucnQpdtoO0FCkSMlpJecpc/2xpmcEHMWUs24wA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T14:27:20Z"
    mac: ENC[AES256_GCM,data:o96O4+OS/muukyZ8kq+CEisJBwP7pQ6EB9b0K6oADT85ZkWweXHcB5gQIelrKnSicPMoEWrMmpf5k15n2TFXJls9InqTSdIuic1946Nyw0JoaTdp0zX19Ko/2XuH/8uvz8EgmcAb8b/B1+54yuR0kRtAylW7LJ/50noOyJxbraY=,iv:O05rWV8Y4UZ1U+SjCnoBuDa7ubR2h83kCKoNUz2dwYU=,tag:CpvS92KCE0tziN7Ya3/NkA==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml|object-storage-configs.yaml|api-token|OPENSEARCH_.*)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: argocd-apps-repo
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
    type: git
    url: https://github.com/nazmang/argocd-apps.git
    username: nazmang
    password: ENC[AES256_GCM,data:YRNpv6/nLUKZ5418mVp0uqpfSZGyIfCVwaJIrBESDc2t6IsMENSvmPx7Gx6hRfWjiY8SL5xXpamgBgTtrNGy9CWvgx4vcelphrAG3iLiU3Mh15B5TV3uS8nOy++1,iv:e60XA+qBZ9GZV0AZynWuF8S/uuQmlozQyZMC7fk/fEA=,tag:uzzHj9e+6VJB/JML/b6LKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcytXSFhGeWxkdWx6SGVW
            L0dGZVJ0ZEdQMndFTnFxUUhNYWFLWjIxY2tZCmFVdWFJU0xqY1VOd3U2YjM2QlJo
            M3FXUzZYcHNyTGVraUZ5RmFyRzJ3WlEKLS0tIFRvVFJEcWlWU3VZRHdpQzZPVlhS
            M0JYOElCMUh1Tm9qY0NBTDFKWDNMQ00KxZhTMb1oeR7RbeLwpqmTh6l2/vy7OZtf
            8t5KSadSO42AT7RyucnQpdtoO0FCkSMlpJecpc/2xpmcEHMWUs24wA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T14:27:20Z"
    mac: ENC[AES256_GCM,data:o96O4+OS/muukyZ8kq+CEisJBwP7pQ6EB9b0K6oADT85ZkWweXHcB5gQIelrKnSicPMoEWrMmpf5k15n2TFXJls9InqTSdIuic1946Nyw0JoaTdp0zX19Ko/2XuH/8uvz8EgmcAb8b/B1+54yuR0kRtAylW7LJ/50noOyJxbraY=,iv:O05rWV8Y4UZ1U+SjCnoBuDa7ubR2h83kCKoNUz2dwYU=,tag:CpvS92KCE0tziN7Ya3/NkA==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml|object-storage-configs.yaml|api-token|OPENSEARCH_.*)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: ai-language-tutor-repo
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
    type: git
    url: https://github.com/nazmang/ai-language-tutor.git
    username: nazmang
    password: ENC[AES256_GCM,data:/eKaqOvwIWAmbzOjVHsd2X3pzVOXCJqW5h2JoZx6IZRzDmuJ1j3loeGY5G4FTwYcPxaU1eEIiwBj/kOyXnQB7GtNfGatMVOokMO/Gj+/R+LwyxhLMsVcHRVTIczX,iv:+Z8uKAi+eqSAIzHc8z9Fkv1yEirX7DbACZlVYM8Ruys=,tag:M+N+rMrjcRWZze/uhkU7AA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcytXSFhGeWxkdWx6SGVW
            L0dGZVJ0ZEdQMndFTnFxUUhNYWFLWjIxY2tZCmFVdWFJU0xqY1VOd3U2YjM2QlJo
            M3FXUzZYcHNyTGVraUZ5RmFyRzJ3WlEKLS0tIFRvVFJEcWlWU3VZRHdpQzZPVlhS
            M0JYOElCMUh1Tm9qY0NBTDFKWDNMQ00KxZhTMb1oeR7RbeLwpqmTh6l2/vy7OZtf
            8t5KSadSO42AT7RyucnQpdtoO0FCkSMlpJecpc/2xpmcEHMWUs24wA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T14:27:20Z"
    mac: ENC[AES256_GCM,data:o96O4+OS/muukyZ8kq+CEisJBwP7pQ6EB9b0K6oADT85ZkWweXHcB5gQIelrKnSicPMoEWrMmpf5k15n2TFXJls9InqTSdIuic1946Nyw0JoaTdp0zX19Ko/2XuH/8uvz8EgmcAb8b/B1+54yuR0kRtAylW7LJ/50noOyJxbraY=,iv:O05rWV8Y4UZ1U+SjCnoBuDa7ubR2h83kCKoNUz2dwYU=,tag:CpvS92KCE0tziN7Ya3/NkA==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml|object-storage-configs.yaml|api-token|OPENSEARCH_.*)$
    version: 3.7.1
