apiVersion: v1
kind: Secret
metadata:
    name: sops-age-key
    namespace: argocd
type: Opaque
stringData:
    SOPS_AGE_KEY: ENC[AES256_GCM,data:iSxI0ew5Z9u4SKWxo/ImDDeRS7C7SWI40fa6zKkJunH4OcujBWacmR3r7Bij3mvCPAyk4HxycrO4XWEBiAYzaW16iUMfmdnvIG0=,iv:bwR98j+LGZhTkr+cG0soA4BZczm32QFM16/Ic6K6tXM=,tag:/sY/ZKocVvz8ULoBr6jIjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZE15UVprM3VxbVJPQnNF
            R1FVZVFqY0VPVDNmbFh6Z0JSYzYxcVpER1EwCk5EOUhwbThQdEpjLzF2TVhQam1R
            cGF4TmZDV1BJc1ExeTlmM2NldWo3UTQKLS0tIDA1ek9YKy8yT3FZZS9NN1pmQWdQ
            ajNOWGV4eGxHK3V1UmNTRnRlTWJiN28Kf2KBgFzoz+zW7k7TgJdQdOVSNSA5MyM/
            ExR5Vr+wIZb5+2JELKthifM+08lLefWxbOATIxFjuuUr4eJ3oOUBbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T17:42:05Z"
    mac: ENC[AES256_GCM,data:zVCw0R8QoYZRrg4+fStOPGvgBjXcOPtiOYKhWf9plmw07wbUL1fXpb4ZyOFNHlH2AfTKVUryLIpsatrKveuvwIuz3acjCKXitx4l80mYG/fAY41O5tuQNSMRgX/OFkJV75Kx9OWhm8t746DSPxpPHoBsJRijRFDlUqjO5n3WBaM=,iv:LFF+XgDDcC9mc52YREV56//neKhHqExlutlSqpxTiR0=,tag:5GFkKIk/2levjcutxBhYwQ==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml|object-storage-configs.yaml|api-token|OPENSEARCH_.*)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: redis-auth
    namespace: argocd
data:
    redis-password: ENC[AES256_GCM,data:jrjpxvg0XQ5ScopeGrAkS3/fpakY3pg3dA0M0pMvU4HMQy0Q,iv:WpYNbvyCnbo7E8u+Wmn2g1rzf7Gy8dWy9QCNUQqeYOs=,tag:BB7opGZ9NHsXOs3zROIb6g==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZE15UVprM3VxbVJPQnNF
            R1FVZVFqY0VPVDNmbFh6Z0JSYzYxcVpER1EwCk5EOUhwbThQdEpjLzF2TVhQam1R
            cGF4TmZDV1BJc1ExeTlmM2NldWo3UTQKLS0tIDA1ek9YKy8yT3FZZS9NN1pmQWdQ
            ajNOWGV4eGxHK3V1UmNTRnRlTWJiN28Kf2KBgFzoz+zW7k7TgJdQdOVSNSA5MyM/
            ExR5Vr+wIZb5+2JELKthifM+08lLefWxbOATIxFjuuUr4eJ3oOUBbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T17:42:05Z"
    mac: ENC[AES256_GCM,data:zVCw0R8QoYZRrg4+fStOPGvgBjXcOPtiOYKhWf9plmw07wbUL1fXpb4ZyOFNHlH2AfTKVUryLIpsatrKveuvwIuz3acjCKXitx4l80mYG/fAY41O5tuQNSMRgX/OFkJV75Kx9OWhm8t746DSPxpPHoBsJRijRFDlUqjO5n3WBaM=,iv:LFF+XgDDcC9mc52YREV56//neKhHqExlutlSqpxTiR0=,tag:5GFkKIk/2levjcutxBhYwQ==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml|object-storage-configs.yaml|api-token|OPENSEARCH_.*)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: argocd-apps-repo
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
    type: git
    url: https://github.com/nazmang/argocd-apps.git
    username: nazmang
    password: ENC[AES256_GCM,data:WNj1j9yoq7HYy+0qY6u6J6sCuI3NmzbBe2zZ/aUN1h4zCz+m4uZ6oWnOKkBBc7mIfBcjW3k+WH9hSs7nO64GeFjw0DDcnBVvEpbPTtiOci9UxTERFXt76tD2VHei,iv:aYmqKUDL5WK9ny+EzLNhnifREN1BLNZNGoDr3wQy6AA=,tag:t9p+0KRvalHqMqJUHzwOjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZE15UVprM3VxbVJPQnNF
            R1FVZVFqY0VPVDNmbFh6Z0JSYzYxcVpER1EwCk5EOUhwbThQdEpjLzF2TVhQam1R
            cGF4TmZDV1BJc1ExeTlmM2NldWo3UTQKLS0tIDA1ek9YKy8yT3FZZS9NN1pmQWdQ
            ajNOWGV4eGxHK3V1UmNTRnRlTWJiN28Kf2KBgFzoz+zW7k7TgJdQdOVSNSA5MyM/
            ExR5Vr+wIZb5+2JELKthifM+08lLefWxbOATIxFjuuUr4eJ3oOUBbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T17:42:05Z"
    mac: ENC[AES256_GCM,data:zVCw0R8QoYZRrg4+fStOPGvgBjXcOPtiOYKhWf9plmw07wbUL1fXpb4ZyOFNHlH2AfTKVUryLIpsatrKveuvwIuz3acjCKXitx4l80mYG/fAY41O5tuQNSMRgX/OFkJV75Kx9OWhm8t746DSPxpPHoBsJRijRFDlUqjO5n3WBaM=,iv:LFF+XgDDcC9mc52YREV56//neKhHqExlutlSqpxTiR0=,tag:5GFkKIk/2levjcutxBhYwQ==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml|object-storage-configs.yaml|api-token|OPENSEARCH_.*)$
    version: 3.7.1
