apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

namespace: external-dns

secretGenerator:
  - name: mikrotik-credentials
    envs:
      - .env
    type: Opaque
