apiVersion: v1
kind: Secret
metadata:
    name: mikrotik-credentials
    namespace: external-dns
data:
    MIKROTIK_BASEURL: ENC[AES256_GCM,data:x/O7wPg8S6YcQjnRNciX1Fq0IFQymx+rr25PvuuozF1MiyQN,iv:7B/GJuCbfXFbWugBmk1LyT52gb5BX51EbGvLjzaRhUg=,tag:am61u9IrWP8d3Dnj0FsxZQ==,type:str]
    MIKROTIK_PASSWORD: ENC[AES256_GCM,data:atXFNGtiFpcL3ITiRPtiUttfN/3DhW1zHRuWNbgJUXTtSzcE,iv:lCxb/CqyA2yBIyapAdecHdumcCG4gIJk7+J4on3YYkE=,tag:/qV+KiQF2/5JTDyXJd6joA==,type:str]
    MIKROTIK_SKIP_TLS_VERIFY: dHJ1ZQ==
    MIKROTIK_USERNAME: ENC[AES256_GCM,data:k1jSZm/AuKA/n3KvhJ1EDA==,iv:hqOIHIEZeGbWvH5sNFCcEfa59xcTd7+FZquLgYDd3PQ=,tag:fNFenPIMKwHE9HVNOKKFNQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNXZIQVlUK2J0cGl0dWQ2
            bU80azhlMG9zVWxpZlpaSXlKY1Z0U2tjYlZzCm9YQVhaRWFrWCsxckRTYlNMOUow
            MUVKZ1VQeTNBbm1aVzFGK2RZL0NxaWcKLS0tIHVIcS8wZ1l2c084VXJlNmVUOHZx
            ZE5kdVczMXpGcXZzakdsTDNFWVUwL28KyVmndZhFjHC9ORG1lnDawobWK9x29YA2
            e7NL/Zrb8IbxtEtKTv/jY/5SyC8LqFo7ItF2Koom8ZLkWMU4bY5qTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-01T18:49:29Z"
    mac: ENC[AES256_GCM,data:uXv+XYPj+FfgEhCs5NJ/dTPc5pACL8i4xglAY5o9seiMtk7BGAqxwVfOpIzWH2zLv8pFdxUBqZlO/kEqBtxUuRK+UIbo8pRGa1SmoC7nlps9cgdK908seyEQK4CSgEQYViDWt5DZxRndQGgEMCT7hXvbiJCT47QRlRflQsNwCDw=,iv:7xebg7osS+hZ3XngO8pSWSzmifWdGslCM0WFpOImoA4=,tag:OGgbmmDQF+Y9uwGwxiwwAA==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL)$
    version: 3.7.1
