image:
  repository: louislam/uptime-kuma
  tag: "2"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3001

persistence:
  enabled: true
  storageClass: "nfs-client"
  size: 5Gi
  accessMode: ReadWriteOnce

ingress:
  enabled: true
  className: nginx
  annotations: {}
  host: uptime-kuma.example.com
  tls: []

httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
    - name: srvx-cc-gateway
      namespace: gateway
  hostname: uptime-kuma.example.com

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

nameOverride: ""
fullnameOverride: ""
