apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ansible-semaphore
  namespace: argocd
spec:
  project: local
  destination:
    server: https://kubernetes.default.svc
    namespace: semaphore
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    helm:
      valueFiles:
        - secrets://https://raw.githubusercontent.com/nazmang/k8s/refs/heads/main/helm-ansible-semaphore/semaphore.values.enc.yaml
    repoURL: "https://cloudhippie.github.io/charts"
    chart: ansible-semaphore
    targetRevision: "14.0.0"
  info:
    - name: artifacthub
      value: "https://artifacthub.io/packages/helm/cloudhippie/ansible-semaphore"
