apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mailhog
  namespace: argocd
spec:  
  project: local
  sources:
    - repoURL: https://codecentric.github.io/helm-charts
      targetRevision: 5.8.0
      chart: mailhog
      helm:
        valueFiles:
          - $values/helm-mailhog/values.yaml
    - repoURL: https://github.com/nazmang/k8s.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: mailhog
  syncPolicy:
    automated: {}
    syncOptions:
        - CreateNamespace=true