apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: minio-stack
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: minio-operator
            path: helm/operator
            wave: "5"
            namespace: minio-operator
            release: minio-operator
          - name: minio-tenant
            path: helm/tenant
            wave: "6"
            namespace: minio-tenant
            release: minio-tenant
  template:
    metadata:
      name: '{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{wave}}'
    spec:
      project: default
      sources:
        - repoURL: 'https://github.com/minio/operator.git'
          targetRevision: master
          path: '{{path}}'
          helm:
            releaseName: '{{release}}'
            valueFiles:
              - $values/helm-minio/minio.values.yaml
        - repoURL: https://github.com/nazmang/k8s.git
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
      dependsOn:
        - minio-operator
