apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

secretGenerator:
  - name: redis-auth
    files:
      - redis-password=redis-password.txt
    type: Opaque

resources:
  - redis-certificate.yaml
