apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redis-tls
  namespace: redis
spec:
  secretName: redis-tls
  duration: 8760h
  renewBefore: 720h
  commonName: redis
  dnsNames:
    - redis
    - redis.redis.svc.cluster.local
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
