apiVersion: batch/v1
kind: Job
metadata:
  name: vault-unseal
  namespace: vault
spec:
  template:
    spec:
      serviceAccountName: vault
      restartPolicy: OnFailure
      containers:
      - name: unseal
        image: hashicorp/vault:1.17.2
        command:
          - /bin/sh
          - -c
          - |
            KEYS=$(yq e '.unseal_keys_b64 | .[0:3][]' /vault-init/vault-init.yaml)
            for k in $KEYS; do
              vault operator unseal "$k"
            done
        env:
          - name: VAULT_ADDR
            value: https://vault.vault.svc.cluster.local:8200
        volumeMounts:
          - name: vault-init
            mountPath: /vault-init
            readOnly: true
      volumes:
        - name: vault-init
          secret:
            secretName: vault-init
